// <auto-generated />
using System.Collections.Generic;
using DepartmentContracts.BindingModels;
using DepartmentContracts.SearchModels;
using DepartmentContracts.ViewModels;

namespace DepartmentContracts.BusinessLogicsContracts
{
    public interface IAcademicPlanLogic
    {
        List<AcademicPlanViewModel>? ReadList(AcademicPlanSearchModel? model);
        AcademicPlanViewModel? ReadElement(AcademicPlanSearchModel model);
        bool Create(AcademicPlanBindingModel model);
        bool Update(AcademicPlanBindingModel model);
        bool Delete(AcademicPlanBindingModel model);
    }
}
