// <auto-generated />
using System.Collections.Generic;
using DepartmentContracts.BindingModels;
using DepartmentContracts.SearchModels;
using DepartmentContracts.ViewModels;

namespace DepartmentContracts.BusinessLogicsContracts
{
    public interface IAcademicPlanRecordLogic
    {
        List<AcademicPlanRecordViewModel>? ReadList(AcademicPlanRecordSearchModel? model);
        AcademicPlanRecordViewModel? ReadElement(AcademicPlanRecordSearchModel model);
        bool Create(AcademicPlanRecordBindingModel model);
        bool Update(AcademicPlanRecordBindingModel model);
        bool Delete(AcademicPlanRecordBindingModel model);
    }
}
