// <auto-generated />
using System.Collections.Generic;
using DepartmentContracts.BindingModels;
using DepartmentContracts.SearchModels;
using DepartmentContracts.ViewModels;

namespace DepartmentContracts.BusinessLogicsContracts
{
    public interface IClassroomLogic
    {
        List<ClassroomViewModel>? ReadList(ClassroomSearchModel? model);
        ClassroomViewModel? ReadElement(ClassroomSearchModel model);
        bool Create(ClassroomBindingModel model);
        bool Update(ClassroomBindingModel model);
        bool Delete(ClassroomBindingModel model);
    }
}
