// <auto-generated />
using System.Collections.Generic;
using DepartmentContracts.BindingModels;
using DepartmentContracts.SearchModels;
using DepartmentContracts.ViewModels;

namespace DepartmentContracts.BusinessLogicsContracts
{
    public interface IDisciplineStudentRecordLogic
    {
        List<DisciplineStudentRecordViewModel>? ReadList(DisciplineStudentRecordSearchModel? model);
        DisciplineStudentRecordViewModel? ReadElement(DisciplineStudentRecordSearchModel model);
        bool Create(DisciplineStudentRecordBindingModel model);
        bool Update(DisciplineStudentRecordBindingModel model);
        bool Delete(DisciplineStudentRecordBindingModel model);
    }
}
