// <auto-generated />
using System.Collections.Generic;
using DepartmentContracts.BindingModels;
using DepartmentContracts.SearchModels;
using DepartmentContracts.ViewModels;

namespace DepartmentContracts.BusinessLogicsContracts
{
    public interface IDisciplineLogic
    {
        List<DisciplineViewModel>? ReadList(DisciplineSearchModel? model);
        DisciplineViewModel? ReadElement(DisciplineSearchModel model);
        bool Create(DisciplineBindingModel model);
        bool Update(DisciplineBindingModel model);
        bool Delete(DisciplineBindingModel model);
    }
}
