// <auto-generated />
using System.Collections.Generic;
using DepartmentContracts.BindingModels;
using DepartmentContracts.SearchModels;
using DepartmentContracts.ViewModels;

namespace DepartmentContracts.BusinessLogicsContracts
{
    public interface IDisciplineBlockLogic
    {
        List<DisciplineBlockViewModel>? ReadList(DisciplineBlockSearchModel? model);
        DisciplineBlockViewModel? ReadElement(DisciplineBlockSearchModel model);
        bool Create(DisciplineBlockBindingModel model);
        bool Update(DisciplineBlockBindingModel model);
        bool Delete(DisciplineBlockBindingModel model);
    }
}
