// <auto-generated />
using System.Collections.Generic;
using DepartmentContracts.BindingModels;
using DepartmentContracts.SearchModels;
using DepartmentContracts.ViewModels;

namespace DepartmentContracts.BusinessLogicsContracts
{
    public interface IEducationDirectionLogic
    {
        List<EducationDirectionViewModel>? ReadList(EducationDirectionSearchModel? model);
        EducationDirectionViewModel? ReadElement(EducationDirectionSearchModel model);
        bool Create(EducationDirectionBindingModel model);
        bool Update(EducationDirectionBindingModel model);
        bool Delete(EducationDirectionBindingModel model);
    }
}
