// <auto-generated />
using System.Collections.Generic;
using DepartmentContracts.BindingModels;
using DepartmentContracts.SearchModels;
using DepartmentContracts.ViewModels;

namespace DepartmentContracts.BusinessLogicsContracts
{
    public interface ILecturerDepartmentPostLogic
    {
        List<LecturerDepartmentPostViewModel>? ReadList(LecturerDepartmentPostSearchModel? model);
        LecturerDepartmentPostViewModel? ReadElement(LecturerDepartmentPostSearchModel model);
        bool Create(LecturerDepartmentPostBindingModel model);
        bool Update(LecturerDepartmentPostBindingModel model);
        bool Delete(LecturerDepartmentPostBindingModel model);
    }
}
