// <auto-generated />
using System.Collections.Generic;
using DepartmentContracts.BindingModels;
using DepartmentContracts.SearchModels;
using DepartmentContracts.ViewModels;

namespace DepartmentContracts.BusinessLogicsContracts
{
    public interface ILecturerStudyPostLogic
    {
        List<LecturerStudyPostViewModel>? ReadList(LecturerStudyPostSearchModel? model);
        LecturerStudyPostViewModel? ReadElement(LecturerStudyPostSearchModel model);
        bool Create(LecturerStudyPostBindingModel model);
        bool Update(LecturerStudyPostBindingModel model);
        bool Delete(LecturerStudyPostBindingModel model);
    }
}
