// <auto-generated />
using System.Collections.Generic;
using DepartmentContracts.BindingModels;
using DepartmentContracts.SearchModels;
using DepartmentContracts.ViewModels;

namespace DepartmentContracts.BusinessLogicsContracts
{
    public interface ILecturerLogic
    {
        List<LecturerViewModel>? ReadList(LecturerSearchModel? model);
        LecturerViewModel? ReadElement(LecturerSearchModel model);
        bool Create(LecturerBindingModel model);
        bool Update(LecturerBindingModel model);
        bool Delete(LecturerBindingModel model);
    }
}
