// <auto-generated />
using System.Collections.Generic;
using DepartmentContracts.BindingModels;
using DepartmentContracts.SearchModels;
using DepartmentContracts.ViewModels;

namespace DepartmentContracts.BusinessLogicsContracts
{
    public interface IStudentOrderLogic
    {
        List<StudentOrderViewModel>? ReadList(StudentOrderSearchModel? model);
        StudentOrderViewModel? ReadElement(StudentOrderSearchModel model);
        bool Create(StudentOrderBindingModel model);
        bool Update(StudentOrderBindingModel model);
        bool Delete(StudentOrderBindingModel model);
    }
}
