// <auto-generated />
using System.Collections.Generic;
using DepartmentContracts.BindingModels;
using DepartmentContracts.SearchModels;
using DepartmentContracts.ViewModels;

namespace DepartmentContracts.BusinessLogicsContracts
{
    public interface IStudentOrderBlockStudentLogic
    {
        List<StudentOrderBlockStudentViewModel>? ReadList(StudentOrderBlockStudentSearchModel? model);
        StudentOrderBlockStudentViewModel? ReadElement(StudentOrderBlockStudentSearchModel model);
        bool Create(StudentOrderBlockStudentBindingModel model);
        bool Update(StudentOrderBlockStudentBindingModel model);
        bool Delete(StudentOrderBlockStudentBindingModel model);
    }
}
