// <auto-generated />
using System.Collections.Generic;
using DepartmentContracts.BindingModels;
using DepartmentContracts.SearchModels;
using DepartmentContracts.ViewModels;

namespace DepartmentContracts.BusinessLogicsContracts
{
    public interface IStudentLogic
    {
        List<StudentViewModel>? ReadList(StudentSearchModel? model);
        StudentViewModel? ReadElement(StudentSearchModel model);
        bool Create(StudentBindingModel model);
        bool Update(StudentBindingModel model);
        bool Delete(StudentBindingModel model);
    }
}
