// <auto-generated />
using System.Collections.Generic;
using DepartmentContracts.BindingModels;
using DepartmentContracts.SearchModels;
using DepartmentContracts.ViewModels;

namespace DepartmentContracts.BusinessLogicsContracts
{
    public interface IStudentGroupLogic
    {
        List<StudentGroupViewModel>? ReadList(StudentGroupSearchModel? model);
        StudentGroupViewModel? ReadElement(StudentGroupSearchModel model);
        bool Create(StudentGroupBindingModel model);
        bool Update(StudentGroupBindingModel model);
        bool Delete(StudentGroupBindingModel model);
    }
}
