// <auto-generated />
using System.Collections.Generic;
using DepartmentContracts.BindingModels;
using DepartmentContracts.SearchModels;
using DepartmentContracts.ViewModels;

namespace DepartmentContracts.BusinessLogicsContracts
{
    public interface IStudentOrderBlockLogic
    {
        List<StudentOrderBlockViewModel>? ReadList(StudentOrderBlockSearchModel? model);
        StudentOrderBlockViewModel? ReadElement(StudentOrderBlockSearchModel model);
        bool Create(StudentOrderBlockBindingModel model);
        bool Update(StudentOrderBlockBindingModel model);
        bool Delete(StudentOrderBlockBindingModel model);
    }
}
