// <auto-generated />

using DepartmentDataModels.Enums;

namespace DepartmentContracts.SearchModels
{
    public class AcademicPlanSearchModel
    {
        public int? Id { get; set; }
        public int? EducationDirectionId { get; set; }
        public AcademicCourse? AcademicCourses { get; set; }
        public string? Year { get; set; }
    }
}
