// <auto-generated />


namespace DepartmentContracts.SearchModels
{
    public class DisciplineBlockSearchModel
    {
        public int? Id { get; set; }
        public string? Title { get; set; }
        public string? DisciplineBlockBlueAsteriskName { get; set; }
        public bool? DisciplineBlockUseForGrouping { get; set; }
        public int? DisciplineBlockOrder { get; set; }
    }
}
