// <auto-generated />


namespace DepartmentContracts.SearchModels
{
    public class DisciplineSearchModel
    {
        public int? Id { get; set; }
        public int? DisciplineBlockId { get; set; }
        public string? DisciplineName { get; set; }
        public string? DisciplineShortName { get; set; }
        public string? DisciplineDescription { get; set; }
        public string? DisciplineBlockBlueAsteriskName { get; set; }
        public bool? HasExam { get; set; }
        public bool? HasCredit { get; set; }
        public bool? HasCourseWork { get; set; }
        public bool? HasCourseProject { get; set; }
    }
}
