// <auto-generated />

using DepartmentDataModels.Enums;

namespace DepartmentContracts.SearchModels
{
    public class DisciplineStudentRecordSearchModel
    {
        public int? Id { get; set; }
        public int? DisciplineId { get; set; }
        public int? StudentId { get; set; }
        public Semesters? Semester { get; set; }
        public string? Variant { get; set; }
        public int? SubGroup { get; set; }
        public MarkType? MarkType { get; set; }
    }
}
