// <auto-generated />

using DepartmentDataModels.Enums;

namespace DepartmentContracts.SearchModels
{
    public class EducationDirectionSearchModel
    {
        public int? Id { get; set; }
        public string? Cipher { get; set; }
        public string? ShortName { get; set; }
        public string? Title { get; set; }
        public EducationDirectionQualification? Qualification { get; set; }
        public string? Profile { get; set; }
        public string? Description { get; set; }
    }
}
