// <auto-generated />

using DepartmentDataModels.Enums;

namespace DepartmentContracts.SearchModels
{
    public class LecturerSearchModel
    {
        public int? Id { get; set; }
        public int? LecturerStudyPostId { get; set; }
        public int? LecturerDepartmentPostId { get; set; }
        public string? FirstName { get; set; }
        public string? LastName { get; set; }
        public string? Patronymic { get; set; }
        public string? Abbreviation { get; set; }
        public DateTime? DateBirth { get; set; }
        public string? Address { get; set; }
        public string? Email { get; set; }
        public string? MobileNumber { get; set; }
        public string? HomeNumber { get; set; }
        public Rank? Rank { get; set; }
        public Rank2? Rank2 { get; set; }
        public string? Description { get; set; }
        public bool? OnlyForPrivate { get; set; }
    }
}
