// <auto-generated />


namespace DepartmentContracts.SearchModels
{
    public class LecturerStudyPostSearchModel
    {
        public int? Id { get; set; }
        public string? StudyPostTitle { get; set; }
        public int? Hours { get; set; }
    }
}
