// <auto-generated />


namespace DepartmentContracts.SearchModels
{
    public class LecturerDepartmentPostSearchModel
    {
        public int? Id { get; set; }
        public string? DepartmentPostTitle { get; set; }
        public int? Order { get; set; }
    }
}
