// <auto-generated />

using DepartmentDataModels.Enums;

namespace DepartmentContracts.SearchModels
{
    public class StudentOrderSearchModel
    {
        public int? Id { get; set; }
        public string? OrderNumber { get; set; }
        public StudentOrderType? StudentOrderType { get; set; }
    }
}
