// <auto-generated />

using DepartmentDataModels.Enums;

namespace DepartmentContracts.SearchModels
{
    public class StudentOrderBlockSearchModel
    {
        public int? Id { get; set; }
        public int? StudentOrderId { get; set; }
        public int? EducationDirectionId { get; set; }
        public StudentOrderType? StudentOrderType { get; set; }
    }
}
