// <auto-generated />

using DepartmentDataModels.Enums;

namespace DepartmentContracts.SearchModels
{
    public class StudentSearchModel
    {
        public int? Id { get; set; }
        public int? StudentGroupId { get; set; }
        public string? NumberOfBook { get; set; }
        public string? FirstName { get; set; }
        public string? LastName { get; set; }
        public string? Patronymic { get; set; }
        public string? Email { get; set; }
        public StudentState? StudentState { get; set; }
        public string? Description { get; set; }
        public bool? IsSteward { get; set; }
    }
}
