// <auto-generated />

using DepartmentDataModels.Enums;

namespace DepartmentContracts.SearchModels
{
    public class StudentGroupSearchModel
    {
        public int? Id { get; set; }
        public int? EducationDirectionId { get; set; }
        public int? CuratorId { get; set; }
        public string? GroupName { get; set; }
        public AcademicCourse? Course { get; set; }
    }
}
