// <auto-generated />
using System;
using DepartmentDatabaseImplement;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DepartmentDatabaseImplement.Migrations
{
    [DbContext(typeof(DepartmentDatabase))]
    [Migration("20260320134452_InitialCreatePostgres")]
    partial class InitialCreatePostgres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DepartmentDatabaseImplement.Models.AcademicPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AcademicCourses")
                        .HasColumnType("integer");

                    b.Property<int?>("EducationDirectionId")
                        .HasColumnType("integer");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EducationDirectionId");

                    b.ToTable("AcademicPlans");
                });

            modelBuilder.Entity("DepartmentDatabaseImplement.Models.AcademicPlanRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AcademicPlanId")
                        .HasColumnType("integer");

                    b.Property<int?>("AcademicPlanRecordParentId")
                        .HasColumnType("integer");

                    b.Property<int>("DisciplineId")
                        .HasColumnType("integer");

                    b.Property<bool>("InDepartment")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActiveSemester")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsChild")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFacultative")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsParent")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsUseInWorkload")
                        .HasColumnType("boolean");

                    b.Property<int>("Semester")
                        .HasColumnType("integer");

                    b.Property<int>("Zet")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AcademicPlanId");

                    b.HasIndex("AcademicPlanRecordParentId");

                    b.HasIndex("DisciplineId");

                    b.ToTable("AcademicPlanRecords");
                });

            modelBuilder.Entity("DepartmentDatabaseImplement.Models.Classroom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<int>("ClassroomType")
                        .HasColumnType("integer");

                    b.Property<bool>("NotUseInSchedule")
                        .HasColumnType("boolean");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Classrooms");
                });

            modelBuilder.Entity("DepartmentDatabaseImplement.Models.Discipline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DisciplineBlockBlueAsteriskName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DisciplineBlockId")
                        .HasColumnType("integer");

                    b.Property<string>("DisciplineDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DisciplineName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DisciplineShortName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DisciplineBlockId");

                    b.ToTable("Disciplines");
                });

            modelBuilder.Entity("DepartmentDatabaseImplement.Models.DisciplineBlock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DisciplineBlockBlueAsteriskName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DisciplineBlockOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("DisciplineBlockUseForGrouping")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DisciplineBlocks");
                });

            modelBuilder.Entity("DepartmentDatabaseImplement.Models.DisciplineStudentRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DisciplineId")
                        .HasColumnType("integer");

                    b.Property<int>("Semester")
                        .HasColumnType("integer");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<int>("SubGroup")
                        .HasColumnType("integer");

                    b.Property<string>("Variant")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DisciplineId");

                    b.HasIndex("StudentId");

                    b.ToTable("DisciplineStudentRecords");
                });

            modelBuilder.Entity("DepartmentDatabaseImplement.Models.EducationDirection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cipher")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Profile")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Qualification")
                        .HasColumnType("integer");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("EducationDirections");
                });

            modelBuilder.Entity("DepartmentDatabaseImplement.Models.Lecturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HomeNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LecturerDepartmentPostId")
                        .HasColumnType("integer");

                    b.Property<int?>("LecturerStudyPostId")
                        .HasColumnType("integer");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("OnlyForPrivate")
                        .HasColumnType("boolean");

                    b.Property<string>("Patronymic")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("bytea");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<int>("Rank2")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LecturerDepartmentPostId");

                    b.HasIndex("LecturerStudyPostId");

                    b.ToTable("Lecturers");
                });

            modelBuilder.Entity("DepartmentDatabaseImplement.Models.LecturerDepartmentPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DepartmentPostTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("LecturerDepartmentPosts");
                });

            modelBuilder.Entity("DepartmentDatabaseImplement.Models.LecturerStudyPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Hours")
                        .HasColumnType("integer");

                    b.Property<string>("StudyPostTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("LecturerStudyPosts");
                });

            modelBuilder.Entity("DepartmentDatabaseImplement.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsSteward")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumberOfBook")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Patronymic")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("bytea");

                    b.Property<int?>("StudentGroupId")
                        .HasColumnType("integer");

                    b.Property<int>("StudentState")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StudentGroupId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("DepartmentDatabaseImplement.Models.StudentGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Course")
                        .HasColumnType("integer");

                    b.Property<int?>("CuratorId")
                        .HasColumnType("integer");

                    b.Property<int>("EducationDirectionId")
                        .HasColumnType("integer");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CuratorId");

                    b.HasIndex("EducationDirectionId");

                    b.ToTable("StudentGroups");
                });

            modelBuilder.Entity("DepartmentDatabaseImplement.Models.StudentOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StudentOrderType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("StudentOrders");
                });

            modelBuilder.Entity("DepartmentDatabaseImplement.Models.StudentOrderBlock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EducationDirectionId")
                        .HasColumnType("integer");

                    b.Property<int>("StudentOrderId")
                        .HasColumnType("integer");

                    b.Property<int>("StudentOrderType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EducationDirectionId");

                    b.HasIndex("StudentOrderId");

                    b.ToTable("StudentOrderBlocks");
                });

            modelBuilder.Entity("DepartmentDatabaseImplement.Models.StudentOrderBlockStudent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("StudentGroupFromId")
                        .HasColumnType("integer");

                    b.Property<int>("StudentGroupToId")
                        .HasColumnType("integer");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<int>("StudentOrderBlockId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StudentGroupFromId");

                    b.HasIndex("StudentGroupToId");

                    b.HasIndex("StudentId");

                    b.HasIndex("StudentOrderBlockId");

                    b.ToTable("StudentOrderBlockStudents");
                });

            modelBuilder.Entity("DepartmentDatabaseImplement.Models.AcademicPlan", b =>
                {
                    b.HasOne("DepartmentDatabaseImplement.Models.EducationDirection", "EducationDirection")
                        .WithMany("AcademicPlans")
                        .HasForeignKey("EducationDirectionId");

                    b.Navigation("EducationDirection");
                });

            modelBuilder.Entity("DepartmentDatabaseImplement.Models.AcademicPlanRecord", b =>
                {
                    b.HasOne("DepartmentDatabaseImplement.Models.AcademicPlan", "AcademicPlan")
                        .WithMany("AcademicPlanRecords")
                        .HasForeignKey("AcademicPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DepartmentDatabaseImplement.Models.AcademicPlanRecord", "AcademicPlanRecordParent")
                        .WithMany("AcademicPlanRecords")
                        .HasForeignKey("AcademicPlanRecordParentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("DepartmentDatabaseImplement.Models.Discipline", "Discipline")
                        .WithMany("AcademicPlanRecords")
                        .HasForeignKey("DisciplineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AcademicPlan");

                    b.Navigation("AcademicPlanRecordParent");

                    b.Navigation("Discipline");
                });

            modelBuilder.Entity("DepartmentDatabaseImplement.Models.Discipline", b =>
                {
                    b.HasOne("DepartmentDatabaseImplement.Models.DisciplineBlock", "DisciplineBlock")
                        .WithMany("Disciplines")
                        .HasForeignKey("DisciplineBlockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DisciplineBlock");
                });

            modelBuilder.Entity("DepartmentDatabaseImplement.Models.DisciplineStudentRecord", b =>
                {
                    b.HasOne("DepartmentDatabaseImplement.Models.Discipline", "Discipline")
                        .WithMany("DisciplineStudentRecords")
                        .HasForeignKey("DisciplineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DepartmentDatabaseImplement.Models.Student", "Student")
                        .WithMany("DisciplineStudentRecords")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Discipline");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("DepartmentDatabaseImplement.Models.Lecturer", b =>
                {
                    b.HasOne("DepartmentDatabaseImplement.Models.LecturerDepartmentPost", "LecturerDepartmentPost")
                        .WithMany("Lecturers")
                        .HasForeignKey("LecturerDepartmentPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DepartmentDatabaseImplement.Models.LecturerStudyPost", "LecturerStudyPost")
                        .WithMany("Lecturers")
                        .HasForeignKey("LecturerStudyPostId");

                    b.Navigation("LecturerDepartmentPost");

                    b.Navigation("LecturerStudyPost");
                });

            modelBuilder.Entity("DepartmentDatabaseImplement.Models.Student", b =>
                {
                    b.HasOne("DepartmentDatabaseImplement.Models.StudentGroup", "StudentGroup")
                        .WithMany("Students")
                        .HasForeignKey("StudentGroupId");

                    b.Navigation("StudentGroup");
                });

            modelBuilder.Entity("DepartmentDatabaseImplement.Models.StudentGroup", b =>
                {
                    b.HasOne("DepartmentDatabaseImplement.Models.Lecturer", "Curator")
                        .WithMany()
                        .HasForeignKey("CuratorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("DepartmentDatabaseImplement.Models.EducationDirection", "EducationDirection")
                        .WithMany("StudentGroups")
                        .HasForeignKey("EducationDirectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curator");

                    b.Navigation("EducationDirection");
                });

            modelBuilder.Entity("DepartmentDatabaseImplement.Models.StudentOrderBlock", b =>
                {
                    b.HasOne("DepartmentDatabaseImplement.Models.EducationDirection", "EducationDirection")
                        .WithMany("StudentOrderBlocks")
                        .HasForeignKey("EducationDirectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DepartmentDatabaseImplement.Models.StudentOrder", "StudentOrder")
                        .WithMany("StudentOrderBlocks")
                        .HasForeignKey("StudentOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EducationDirection");

                    b.Navigation("StudentOrder");
                });

            modelBuilder.Entity("DepartmentDatabaseImplement.Models.StudentOrderBlockStudent", b =>
                {
                    b.HasOne("DepartmentDatabaseImplement.Models.StudentGroup", "StudentGroupFrom")
                        .WithMany("StudentFromOrderBlockStudents")
                        .HasForeignKey("StudentGroupFromId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DepartmentDatabaseImplement.Models.StudentGroup", "StudentGroupTo")
                        .WithMany("StudentToOrderBlockStudents")
                        .HasForeignKey("StudentGroupToId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DepartmentDatabaseImplement.Models.Student", "Student")
                        .WithMany("StudentOrderBlockStudents")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DepartmentDatabaseImplement.Models.StudentOrderBlock", "StudentOrderBlock")
                        .WithMany("StudentOrderBlockStudents")
                        .HasForeignKey("StudentOrderBlockId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("StudentGroupFrom");

                    b.Navigation("StudentGroupTo");

                    b.Navigation("StudentOrderBlock");
                });

            modelBuilder.Entity("DepartmentDatabaseImplement.Models.AcademicPlan", b =>
                {
                    b.Navigation("AcademicPlanRecords");
                });

            modelBuilder.Entity("DepartmentDatabaseImplement.Models.AcademicPlanRecord", b =>
                {
                    b.Navigation("AcademicPlanRecords");
                });

            modelBuilder.Entity("DepartmentDatabaseImplement.Models.Discipline", b =>
                {
                    b.Navigation("AcademicPlanRecords");

                    b.Navigation("DisciplineStudentRecords");
                });

            modelBuilder.Entity("DepartmentDatabaseImplement.Models.DisciplineBlock", b =>
                {
                    b.Navigation("Disciplines");
                });

            modelBuilder.Entity("DepartmentDatabaseImplement.Models.EducationDirection", b =>
                {
                    b.Navigation("AcademicPlans");

                    b.Navigation("StudentGroups");

                    b.Navigation("StudentOrderBlocks");
                });

            modelBuilder.Entity("DepartmentDatabaseImplement.Models.LecturerDepartmentPost", b =>
                {
                    b.Navigation("Lecturers");
                });

            modelBuilder.Entity("DepartmentDatabaseImplement.Models.LecturerStudyPost", b =>
                {
                    b.Navigation("Lecturers");
                });

            modelBuilder.Entity("DepartmentDatabaseImplement.Models.Student", b =>
                {
                    b.Navigation("DisciplineStudentRecords");

                    b.Navigation("StudentOrderBlockStudents");
                });

            modelBuilder.Entity("DepartmentDatabaseImplement.Models.StudentGroup", b =>
                {
                    b.Navigation("StudentFromOrderBlockStudents");

                    b.Navigation("StudentToOrderBlockStudents");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("DepartmentDatabaseImplement.Models.StudentOrder", b =>
                {
                    b.Navigation("StudentOrderBlocks");
                });

            modelBuilder.Entity("DepartmentDatabaseImplement.Models.StudentOrderBlock", b =>
                {
                    b.Navigation("StudentOrderBlockStudents");
                });
#pragma warning restore 612, 618
        }
    }
}
