// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.Extensions.Logging;
using DepartmentContracts.BindingModels;
using DepartmentContracts.BusinessLogicsContracts;
using DepartmentContracts.SearchModels;
using DepartmentContracts.StoragesContracts;
using DepartmentContracts.ViewModels;

namespace DepartmentBusinessLogic.BusinessLogics
{
    public class AcademicPlanLogic : IAcademicPlanLogic
    {
        private readonly ILogger _logger;

        private readonly IAcademicPlanStorage _AcademicPlanStorage;

        public AcademicPlanLogic(ILogger<AcademicPlanLogic> logger, IAcademicPlanStorage AcademicPlanStorage)
        {
            _logger = logger;
            _AcademicPlanStorage = AcademicPlanStorage;
        }

        public List<AcademicPlanViewModel>? ReadList(AcademicPlanSearchModel? model)
        {
            _logger.LogInformation("ReadList. Id:{Id}", model?.Id);
            var list = model == null ? _AcademicPlanStorage.GetFullList() : _AcademicPlanStorage.GetFilteredList(model);
            if (list == null)
            {
                _logger.LogWarning("ReadList return null list");
                return null;
            }
            _logger.LogInformation("ReadList. Count:{Count}", list.Count);
            return list;
        }

        public AcademicPlanViewModel? ReadElement(AcademicPlanSearchModel model)
        {
            if (model == null) throw new ArgumentNullException(nameof(model));
            _logger.LogInformation("ReadElement. Id:{Id}", model.Id);
            var element = _AcademicPlanStorage.GetElement(model);
            if (element == null)
            {
                _logger.LogWarning("ReadElement element not found");
                return null;
            }
            _logger.LogInformation("ReadElement find. Id:{Id}", element.Id);
            return element;
        }

        public bool Create(AcademicPlanBindingModel model)
        {
            CheckModel(model);
            if (_AcademicPlanStorage.Insert(model) == null)
            {
                _logger.LogWarning("Insert operation failed");
                return false;
            }
            return true;
        }

        public bool Update(AcademicPlanBindingModel model)
        {
            CheckModel(model);
            if (_AcademicPlanStorage.Update(model) == null)
            {
                _logger.LogWarning("Update operation failed");
                return false;
            }
            return true;
        }

        public bool Delete(AcademicPlanBindingModel model)
        {
            CheckModel(model, false);
            _logger.LogInformation("Delete. Id:{Id}", model.Id);
            if (_AcademicPlanStorage.Delete(model) == null)
            {
                _logger.LogWarning("Delete operation failed");
                return false;
            }
            return true;
        }

        private void CheckModel(AcademicPlanBindingModel model, bool withParams = true)
        {
            if (model == null) throw new ArgumentNullException(nameof(model));
            if (!withParams) return;
            if (model.EducationDirectionId <= 0)
                throw new ArgumentNullException("", nameof(model.EducationDirectionId));
        }
    }
}
