// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.Extensions.Logging;
using DepartmentContracts.BindingModels;
using DepartmentContracts.BusinessLogicsContracts;
using DepartmentContracts.SearchModels;
using DepartmentContracts.StoragesContracts;
using DepartmentContracts.ViewModels;

namespace DepartmentBusinessLogic.BusinessLogics
{
    public class DisciplineLogic : IDisciplineLogic
    {
        private readonly ILogger _logger;

        private readonly IDisciplineStorage _DisciplineStorage;

        public DisciplineLogic(ILogger<DisciplineLogic> logger, IDisciplineStorage DisciplineStorage)
        {
            _logger = logger;
            _DisciplineStorage = DisciplineStorage;
        }

        public List<DisciplineViewModel>? ReadList(DisciplineSearchModel? model)
        {
            _logger.LogInformation("ReadList. Id:{Id}", model?.Id);
            var list = model == null ? _DisciplineStorage.GetFullList() : _DisciplineStorage.GetFilteredList(model);
            if (list == null)
            {
                _logger.LogWarning("ReadList return null list");
                return null;
            }
            _logger.LogInformation("ReadList. Count:{Count}", list.Count);
            return list;
        }

        public DisciplineViewModel? ReadElement(DisciplineSearchModel model)
        {
            if (model == null) throw new ArgumentNullException(nameof(model));
            _logger.LogInformation("ReadElement. Id:{Id}", model.Id);
            var element = _DisciplineStorage.GetElement(model);
            if (element == null)
            {
                _logger.LogWarning("ReadElement element not found");
                return null;
            }
            _logger.LogInformation("ReadElement find. Id:{Id}", element.Id);
            return element;
        }

        public bool Create(DisciplineBindingModel model)
        {
            CheckModel(model);
            if (_DisciplineStorage.Insert(model) == null)
            {
                _logger.LogWarning("Insert operation failed");
                return false;
            }
            return true;
        }

        public bool Update(DisciplineBindingModel model)
        {
            CheckModel(model);
            if (_DisciplineStorage.Update(model) == null)
            {
                _logger.LogWarning("Update operation failed");
                return false;
            }
            return true;
        }

        public bool Delete(DisciplineBindingModel model)
        {
            CheckModel(model, false);
            _logger.LogInformation("Delete. Id:{Id}", model.Id);
            if (_DisciplineStorage.Delete(model) == null)
            {
                _logger.LogWarning("Delete operation failed");
                return false;
            }
            return true;
        }

        private void CheckModel(DisciplineBindingModel model, bool withParams = true)
        {
            if (model == null) throw new ArgumentNullException(nameof(model));
            if (!withParams) return;
            if (string.IsNullOrEmpty(model.DisciplineName))
                throw new ArgumentNullException("", nameof(model.DisciplineName));
            if (string.IsNullOrEmpty(model.DisciplineShortName))
                throw new ArgumentNullException("", nameof(model.DisciplineShortName));
            if (string.IsNullOrEmpty(model.DisciplineDescription))
                throw new ArgumentNullException("", nameof(model.DisciplineDescription));
            if (string.IsNullOrEmpty(model.DisciplineBlockBlueAsteriskName))
                throw new ArgumentNullException("", nameof(model.DisciplineBlockBlueAsteriskName));
            if (model.DisciplineBlockId <= 0)
                throw new ArgumentNullException("", nameof(model.DisciplineBlockId));
            var element = _DisciplineStorage.GetElement(new DisciplineSearchModel
            {
                DisciplineName = model.DisciplineName
            });
            if (element != null && element.Id != model.Id)
                throw new InvalidOperationException("");
        }
    }
}
