// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.Extensions.Logging;
using DepartmentContracts.BindingModels;
using DepartmentContracts.BusinessLogicsContracts;
using DepartmentContracts.SearchModels;
using DepartmentContracts.StoragesContracts;
using DepartmentContracts.ViewModels;

namespace DepartmentBusinessLogic.BusinessLogics
{
    public class DisciplineBlockLogic : IDisciplineBlockLogic
    {
        private readonly ILogger _logger;

        private readonly IDisciplineBlockStorage _DisciplineBlockStorage;

        public DisciplineBlockLogic(ILogger<DisciplineBlockLogic> logger, IDisciplineBlockStorage DisciplineBlockStorage)
        {
            _logger = logger;
            _DisciplineBlockStorage = DisciplineBlockStorage;
        }

        public List<DisciplineBlockViewModel>? ReadList(DisciplineBlockSearchModel? model)
        {
            _logger.LogInformation("ReadList. Id:{Id}", model?.Id);
            var list = model == null ? _DisciplineBlockStorage.GetFullList() : _DisciplineBlockStorage.GetFilteredList(model);
            if (list == null)
            {
                _logger.LogWarning("ReadList return null list");
                return null;
            }
            _logger.LogInformation("ReadList. Count:{Count}", list.Count);
            return list;
        }

        public DisciplineBlockViewModel? ReadElement(DisciplineBlockSearchModel model)
        {
            if (model == null) throw new ArgumentNullException(nameof(model));
            _logger.LogInformation("ReadElement. Id:{Id}", model.Id);
            var element = _DisciplineBlockStorage.GetElement(model);
            if (element == null)
            {
                _logger.LogWarning("ReadElement element not found");
                return null;
            }
            _logger.LogInformation("ReadElement find. Id:{Id}", element.Id);
            return element;
        }

        public bool Create(DisciplineBlockBindingModel model)
        {
            CheckModel(model);
            if (_DisciplineBlockStorage.Insert(model) == null)
            {
                _logger.LogWarning("Insert operation failed");
                return false;
            }
            return true;
        }

        public bool Update(DisciplineBlockBindingModel model)
        {
            CheckModel(model);
            if (_DisciplineBlockStorage.Update(model) == null)
            {
                _logger.LogWarning("Update operation failed");
                return false;
            }
            return true;
        }

        public bool Delete(DisciplineBlockBindingModel model)
        {
            CheckModel(model, false);
            _logger.LogInformation("Delete. Id:{Id}", model.Id);
            if (_DisciplineBlockStorage.Delete(model) == null)
            {
                _logger.LogWarning("Delete operation failed");
                return false;
            }
            return true;
        }

        private void CheckModel(DisciplineBlockBindingModel model, bool withParams = true)
        {
            if (model == null) throw new ArgumentNullException(nameof(model));
            if (!withParams) return;
            if (string.IsNullOrEmpty(model.Title))
                throw new ArgumentNullException("", nameof(model.Title));
            if (string.IsNullOrEmpty(model.DisciplineBlockBlueAsteriskName))
                throw new ArgumentNullException("", nameof(model.DisciplineBlockBlueAsteriskName));
            var element = _DisciplineBlockStorage.GetElement(new DisciplineBlockSearchModel
            {
                Title = model.Title
            });
            if (element != null && element.Id != model.Id)
                throw new InvalidOperationException("");
        }
    }
}
