// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.Extensions.Logging;
using DepartmentContracts.BindingModels;
using DepartmentContracts.BusinessLogicsContracts;
using DepartmentContracts.SearchModels;
using DepartmentContracts.StoragesContracts;
using DepartmentContracts.ViewModels;

namespace DepartmentBusinessLogic.BusinessLogics
{
    public class DisciplineStudentRecordLogic : IDisciplineStudentRecordLogic
    {
        private readonly ILogger _logger;

        private readonly IDisciplineStudentRecordStorage _DisciplineStudentRecordStorage;

        public DisciplineStudentRecordLogic(ILogger<DisciplineStudentRecordLogic> logger, IDisciplineStudentRecordStorage DisciplineStudentRecordStorage)
        {
            _logger = logger;
            _DisciplineStudentRecordStorage = DisciplineStudentRecordStorage;
        }

        public List<DisciplineStudentRecordViewModel>? ReadList(DisciplineStudentRecordSearchModel? model)
        {
            _logger.LogInformation("ReadList. Id:{Id}", model?.Id);
            var list = model == null ? _DisciplineStudentRecordStorage.GetFullList() : _DisciplineStudentRecordStorage.GetFilteredList(model);
            if (list == null)
            {
                _logger.LogWarning("ReadList return null list");
                return null;
            }
            _logger.LogInformation("ReadList. Count:{Count}", list.Count);
            return list;
        }

        public DisciplineStudentRecordViewModel? ReadElement(DisciplineStudentRecordSearchModel model)
        {
            if (model == null) throw new ArgumentNullException(nameof(model));
            _logger.LogInformation("ReadElement. Id:{Id}", model.Id);
            var element = _DisciplineStudentRecordStorage.GetElement(model);
            if (element == null)
            {
                _logger.LogWarning("ReadElement element not found");
                return null;
            }
            _logger.LogInformation("ReadElement find. Id:{Id}", element.Id);
            return element;
        }

        public bool Create(DisciplineStudentRecordBindingModel model)
        {
            CheckModel(model);
            if (_DisciplineStudentRecordStorage.Insert(model) == null)
            {
                _logger.LogWarning("Insert operation failed");
                return false;
            }
            return true;
        }

        public bool Update(DisciplineStudentRecordBindingModel model)
        {
            CheckModel(model);
            if (_DisciplineStudentRecordStorage.Update(model) == null)
            {
                _logger.LogWarning("Update operation failed");
                return false;
            }
            return true;
        }

        public bool Delete(DisciplineStudentRecordBindingModel model)
        {
            CheckModel(model, false);
            _logger.LogInformation("Delete. Id:{Id}", model.Id);
            if (_DisciplineStudentRecordStorage.Delete(model) == null)
            {
                _logger.LogWarning("Delete operation failed");
                return false;
            }
            return true;
        }

        private void CheckModel(DisciplineStudentRecordBindingModel model, bool withParams = true)
        {
            if (model == null) throw new ArgumentNullException(nameof(model));
            if (!withParams) return;
            if (string.IsNullOrEmpty(model.Variant))
                throw new ArgumentNullException("", nameof(model.Variant));
            if (model.DisciplineId <= 0)
                throw new ArgumentNullException("", nameof(model.DisciplineId));
            if (model.StudentId <= 0)
                throw new ArgumentNullException("", nameof(model.StudentId));
        }
    }
}
