// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.Extensions.Logging;
using DepartmentContracts.BindingModels;
using DepartmentContracts.BusinessLogicsContracts;
using DepartmentContracts.SearchModels;
using DepartmentContracts.StoragesContracts;
using DepartmentContracts.ViewModels;

namespace DepartmentBusinessLogic.BusinessLogics
{
    public class EducationDirectionLogic : IEducationDirectionLogic
    {
        private readonly ILogger _logger;

        private readonly IEducationDirectionStorage _EducationDirectionStorage;

        public EducationDirectionLogic(ILogger<EducationDirectionLogic> logger, IEducationDirectionStorage EducationDirectionStorage)
        {
            _logger = logger;
            _EducationDirectionStorage = EducationDirectionStorage;
        }

        public List<EducationDirectionViewModel>? ReadList(EducationDirectionSearchModel? model)
        {
            _logger.LogInformation("ReadList. Id:{Id}", model?.Id);
            var list = model == null ? _EducationDirectionStorage.GetFullList() : _EducationDirectionStorage.GetFilteredList(model);
            if (list == null)
            {
                _logger.LogWarning("ReadList return null list");
                return null;
            }
            _logger.LogInformation("ReadList. Count:{Count}", list.Count);
            return list;
        }

        public EducationDirectionViewModel? ReadElement(EducationDirectionSearchModel model)
        {
            if (model == null) throw new ArgumentNullException(nameof(model));
            _logger.LogInformation("ReadElement. Id:{Id}", model.Id);
            var element = _EducationDirectionStorage.GetElement(model);
            if (element == null)
            {
                _logger.LogWarning("ReadElement element not found");
                return null;
            }
            _logger.LogInformation("ReadElement find. Id:{Id}", element.Id);
            return element;
        }

        public bool Create(EducationDirectionBindingModel model)
        {
            CheckModel(model);
            if (_EducationDirectionStorage.Insert(model) == null)
            {
                _logger.LogWarning("Insert operation failed");
                return false;
            }
            return true;
        }

        public bool Update(EducationDirectionBindingModel model)
        {
            CheckModel(model);
            if (_EducationDirectionStorage.Update(model) == null)
            {
                _logger.LogWarning("Update operation failed");
                return false;
            }
            return true;
        }

        public bool Delete(EducationDirectionBindingModel model)
        {
            CheckModel(model, false);
            _logger.LogInformation("Delete. Id:{Id}", model.Id);
            if (_EducationDirectionStorage.Delete(model) == null)
            {
                _logger.LogWarning("Delete operation failed");
                return false;
            }
            return true;
        }

        private void CheckModel(EducationDirectionBindingModel model, bool withParams = true)
        {
            if (model == null) throw new ArgumentNullException(nameof(model));
            if (!withParams) return;
            if (string.IsNullOrEmpty(model.Cipher))
                throw new ArgumentNullException("", nameof(model.Cipher));
            if (string.IsNullOrEmpty(model.ShortName))
                throw new ArgumentNullException("", nameof(model.ShortName));
            if (string.IsNullOrEmpty(model.Title))
                throw new ArgumentNullException("", nameof(model.Title));
            if (string.IsNullOrEmpty(model.Profile))
                throw new ArgumentNullException("", nameof(model.Profile));
            if (string.IsNullOrEmpty(model.Description))
                throw new ArgumentNullException("", nameof(model.Description));
            var element = _EducationDirectionStorage.GetElement(new EducationDirectionSearchModel
            {
                ShortName = model.ShortName
            });
            if (element != null && element.Id != model.Id)
                throw new InvalidOperationException("");
        }
    }
}
