// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.Extensions.Logging;
using DepartmentContracts.BindingModels;
using DepartmentContracts.BusinessLogicsContracts;
using DepartmentContracts.SearchModels;
using DepartmentContracts.StoragesContracts;
using DepartmentContracts.ViewModels;

namespace DepartmentBusinessLogic.BusinessLogics
{
    public class LecturerStudyPostLogic : ILecturerStudyPostLogic
    {
        private readonly ILogger _logger;

        private readonly ILecturerStudyPostStorage _LecturerStudyPostStorage;

        public LecturerStudyPostLogic(ILogger<LecturerStudyPostLogic> logger, ILecturerStudyPostStorage LecturerStudyPostStorage)
        {
            _logger = logger;
            _LecturerStudyPostStorage = LecturerStudyPostStorage;
        }

        public List<LecturerStudyPostViewModel>? ReadList(LecturerStudyPostSearchModel? model)
        {
            _logger.LogInformation("ReadList. Id:{Id}", model?.Id);
            var list = model == null ? _LecturerStudyPostStorage.GetFullList() : _LecturerStudyPostStorage.GetFilteredList(model);
            if (list == null)
            {
                _logger.LogWarning("ReadList return null list");
                return null;
            }
            _logger.LogInformation("ReadList. Count:{Count}", list.Count);
            return list;
        }

        public LecturerStudyPostViewModel? ReadElement(LecturerStudyPostSearchModel model)
        {
            if (model == null) throw new ArgumentNullException(nameof(model));
            _logger.LogInformation("ReadElement. Id:{Id}", model.Id);
            var element = _LecturerStudyPostStorage.GetElement(model);
            if (element == null)
            {
                _logger.LogWarning("ReadElement element not found");
                return null;
            }
            _logger.LogInformation("ReadElement find. Id:{Id}", element.Id);
            return element;
        }

        public bool Create(LecturerStudyPostBindingModel model)
        {
            CheckModel(model);
            if (_LecturerStudyPostStorage.Insert(model) == null)
            {
                _logger.LogWarning("Insert operation failed");
                return false;
            }
            return true;
        }

        public bool Update(LecturerStudyPostBindingModel model)
        {
            CheckModel(model);
            if (_LecturerStudyPostStorage.Update(model) == null)
            {
                _logger.LogWarning("Update operation failed");
                return false;
            }
            return true;
        }

        public bool Delete(LecturerStudyPostBindingModel model)
        {
            CheckModel(model, false);
            _logger.LogInformation("Delete. Id:{Id}", model.Id);
            if (_LecturerStudyPostStorage.Delete(model) == null)
            {
                _logger.LogWarning("Delete operation failed");
                return false;
            }
            return true;
        }

        private void CheckModel(LecturerStudyPostBindingModel model, bool withParams = true)
        {
            if (model == null) throw new ArgumentNullException(nameof(model));
            if (!withParams) return;
            if (string.IsNullOrEmpty(model.StudyPostTitle))
                throw new ArgumentNullException("", nameof(model.StudyPostTitle));
        }
    }
}
