// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.Extensions.Logging;
using DepartmentContracts.BindingModels;
using DepartmentContracts.BusinessLogicsContracts;
using DepartmentContracts.SearchModels;
using DepartmentContracts.StoragesContracts;
using DepartmentContracts.ViewModels;

namespace DepartmentBusinessLogic.BusinessLogics
{
    public class StudentOrderBlockStudentLogic : IStudentOrderBlockStudentLogic
    {
        private readonly ILogger _logger;

        private readonly IStudentOrderBlockStudentStorage _StudentOrderBlockStudentStorage;

        public StudentOrderBlockStudentLogic(ILogger<StudentOrderBlockStudentLogic> logger, IStudentOrderBlockStudentStorage StudentOrderBlockStudentStorage)
        {
            _logger = logger;
            _StudentOrderBlockStudentStorage = StudentOrderBlockStudentStorage;
        }

        public List<StudentOrderBlockStudentViewModel>? ReadList(StudentOrderBlockStudentSearchModel? model)
        {
            _logger.LogInformation("ReadList. Id:{Id}", model?.Id);
            var list = model == null ? _StudentOrderBlockStudentStorage.GetFullList() : _StudentOrderBlockStudentStorage.GetFilteredList(model);
            if (list == null)
            {
                _logger.LogWarning("ReadList return null list");
                return null;
            }
            _logger.LogInformation("ReadList. Count:{Count}", list.Count);
            return list;
        }

        public StudentOrderBlockStudentViewModel? ReadElement(StudentOrderBlockStudentSearchModel model)
        {
            if (model == null) throw new ArgumentNullException(nameof(model));
            _logger.LogInformation("ReadElement. Id:{Id}", model.Id);
            var element = _StudentOrderBlockStudentStorage.GetElement(model);
            if (element == null)
            {
                _logger.LogWarning("ReadElement element not found");
                return null;
            }
            _logger.LogInformation("ReadElement find. Id:{Id}", element.Id);
            return element;
        }

        public bool Create(StudentOrderBlockStudentBindingModel model)
        {
            CheckModel(model);
            if (_StudentOrderBlockStudentStorage.Insert(model) == null)
            {
                _logger.LogWarning("Insert operation failed");
                return false;
            }
            return true;
        }

        public bool Update(StudentOrderBlockStudentBindingModel model)
        {
            CheckModel(model);
            if (_StudentOrderBlockStudentStorage.Update(model) == null)
            {
                _logger.LogWarning("Update operation failed");
                return false;
            }
            return true;
        }

        public bool Delete(StudentOrderBlockStudentBindingModel model)
        {
            CheckModel(model, false);
            _logger.LogInformation("Delete. Id:{Id}", model.Id);
            if (_StudentOrderBlockStudentStorage.Delete(model) == null)
            {
                _logger.LogWarning("Delete operation failed");
                return false;
            }
            return true;
        }

        private void CheckModel(StudentOrderBlockStudentBindingModel model, bool withParams = true)
        {
            if (model == null) throw new ArgumentNullException(nameof(model));
            if (!withParams) return;
            if (model.StudentOrderBlockId <= 0)
                throw new ArgumentNullException("", nameof(model.StudentOrderBlockId));
            if (model.StudentId <= 0)
                throw new ArgumentNullException("", nameof(model.StudentId));
            if (model.StudentGroupFromId <= 0)
                throw new ArgumentNullException("", nameof(model.StudentGroupFromId));
            if (model.StudentGroupToId <= 0)
                throw new ArgumentNullException("", nameof(model.StudentGroupToId));
        }
    }
}
