// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.Extensions.Logging;
using DepartmentContracts.BindingModels;
using DepartmentContracts.BusinessLogicsContracts;
using DepartmentContracts.SearchModels;
using DepartmentContracts.StoragesContracts;
using DepartmentContracts.ViewModels;

namespace DepartmentBusinessLogic.BusinessLogics
{
    public class StudentOrderLogic : IStudentOrderLogic
    {
        private readonly ILogger _logger;

        private readonly IStudentOrderStorage _StudentOrderStorage;

        public StudentOrderLogic(ILogger<StudentOrderLogic> logger, IStudentOrderStorage StudentOrderStorage)
        {
            _logger = logger;
            _StudentOrderStorage = StudentOrderStorage;
        }

        public List<StudentOrderViewModel>? ReadList(StudentOrderSearchModel? model)
        {
            _logger.LogInformation("ReadList. Id:{Id}", model?.Id);
            var list = model == null ? _StudentOrderStorage.GetFullList() : _StudentOrderStorage.GetFilteredList(model);
            if (list == null)
            {
                _logger.LogWarning("ReadList return null list");
                return null;
            }
            _logger.LogInformation("ReadList. Count:{Count}", list.Count);
            return list;
        }

        public StudentOrderViewModel? ReadElement(StudentOrderSearchModel model)
        {
            if (model == null) throw new ArgumentNullException(nameof(model));
            _logger.LogInformation("ReadElement. Id:{Id}", model.Id);
            var element = _StudentOrderStorage.GetElement(model);
            if (element == null)
            {
                _logger.LogWarning("ReadElement element not found");
                return null;
            }
            _logger.LogInformation("ReadElement find. Id:{Id}", element.Id);
            return element;
        }

        public bool Create(StudentOrderBindingModel model)
        {
            CheckModel(model);
            if (_StudentOrderStorage.Insert(model) == null)
            {
                _logger.LogWarning("Insert operation failed");
                return false;
            }
            return true;
        }

        public bool Update(StudentOrderBindingModel model)
        {
            CheckModel(model);
            if (_StudentOrderStorage.Update(model) == null)
            {
                _logger.LogWarning("Update operation failed");
                return false;
            }
            return true;
        }

        public bool Delete(StudentOrderBindingModel model)
        {
            CheckModel(model, false);
            _logger.LogInformation("Delete. Id:{Id}", model.Id);
            if (_StudentOrderStorage.Delete(model) == null)
            {
                _logger.LogWarning("Delete operation failed");
                return false;
            }
            return true;
        }

        private void CheckModel(StudentOrderBindingModel model, bool withParams = true)
        {
            if (model == null) throw new ArgumentNullException(nameof(model));
            if (!withParams) return;
            if (string.IsNullOrEmpty(model.OrderNumber))
                throw new ArgumentNullException("", nameof(model.OrderNumber));
        }
    }
}
