// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.Extensions.Logging;
using DepartmentContracts.BindingModels;
using DepartmentContracts.BusinessLogicsContracts;
using DepartmentContracts.SearchModels;
using DepartmentContracts.StoragesContracts;
using DepartmentContracts.ViewModels;

namespace DepartmentBusinessLogic.BusinessLogics
{
    public class StudentLogic : IStudentLogic
    {
        private readonly ILogger _logger;

        private readonly IStudentStorage _StudentStorage;

        public StudentLogic(ILogger<StudentLogic> logger, IStudentStorage StudentStorage)
        {
            _logger = logger;
            _StudentStorage = StudentStorage;
        }

        public List<StudentViewModel>? ReadList(StudentSearchModel? model)
        {
            _logger.LogInformation("ReadList. Id:{Id}", model?.Id);
            var list = model == null ? _StudentStorage.GetFullList() : _StudentStorage.GetFilteredList(model);
            if (list == null)
            {
                _logger.LogWarning("ReadList return null list");
                return null;
            }
            _logger.LogInformation("ReadList. Count:{Count}", list.Count);
            return list;
        }

        public StudentViewModel? ReadElement(StudentSearchModel model)
        {
            if (model == null) throw new ArgumentNullException(nameof(model));
            _logger.LogInformation("ReadElement. Id:{Id}", model.Id);
            var element = _StudentStorage.GetElement(model);
            if (element == null)
            {
                _logger.LogWarning("ReadElement element not found");
                return null;
            }
            _logger.LogInformation("ReadElement find. Id:{Id}", element.Id);
            return element;
        }

        public bool Create(StudentBindingModel model)
        {
            CheckModel(model);
            if (_StudentStorage.Insert(model) == null)
            {
                _logger.LogWarning("Insert operation failed");
                return false;
            }
            return true;
        }

        public bool Update(StudentBindingModel model)
        {
            CheckModel(model);
            if (_StudentStorage.Update(model) == null)
            {
                _logger.LogWarning("Update operation failed");
                return false;
            }
            return true;
        }

        public bool Delete(StudentBindingModel model)
        {
            CheckModel(model, false);
            _logger.LogInformation("Delete. Id:{Id}", model.Id);
            if (_StudentStorage.Delete(model) == null)
            {
                _logger.LogWarning("Delete operation failed");
                return false;
            }
            return true;
        }

        private void CheckModel(StudentBindingModel model, bool withParams = true)
        {
            if (model == null) throw new ArgumentNullException(nameof(model));
            if (!withParams) return;
            if (string.IsNullOrEmpty(model.NumberOfBook))
                throw new ArgumentNullException("", nameof(model.NumberOfBook));
            if (string.IsNullOrEmpty(model.FirstName))
                throw new ArgumentNullException("", nameof(model.FirstName));
            if (string.IsNullOrEmpty(model.LastName))
                throw new ArgumentNullException("", nameof(model.LastName));
            if (string.IsNullOrEmpty(model.Patronymic))
                throw new ArgumentNullException("", nameof(model.Patronymic));
            if (string.IsNullOrEmpty(model.Email))
                throw new ArgumentNullException("", nameof(model.Email));
            if (string.IsNullOrEmpty(model.Description))
                throw new ArgumentNullException("", nameof(model.Description));
            if (model.StudentGroupId <= 0)
                throw new ArgumentNullException("", nameof(model.StudentGroupId));
            var element = _StudentStorage.GetElement(new StudentSearchModel
            {
                FirstName = model.FirstName
            });
            if (element != null && element.Id != model.Id)
                throw new InvalidOperationException("");
        }
    }
}
