// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.Extensions.Logging;
using DepartmentContracts.BindingModels;
using DepartmentContracts.BusinessLogicsContracts;
using DepartmentContracts.SearchModels;
using DepartmentContracts.StoragesContracts;
using DepartmentContracts.ViewModels;

namespace DepartmentBusinessLogic.BusinessLogics
{
    public class StudentGroupLogic : IStudentGroupLogic
    {
        private readonly ILogger _logger;

        private readonly IStudentGroupStorage _StudentGroupStorage;

        public StudentGroupLogic(ILogger<StudentGroupLogic> logger, IStudentGroupStorage StudentGroupStorage)
        {
            _logger = logger;
            _StudentGroupStorage = StudentGroupStorage;
        }

        public List<StudentGroupViewModel>? ReadList(StudentGroupSearchModel? model)
        {
            _logger.LogInformation("ReadList. Id:{Id}", model?.Id);
            var list = model == null ? _StudentGroupStorage.GetFullList() : _StudentGroupStorage.GetFilteredList(model);
            if (list == null)
            {
                _logger.LogWarning("ReadList return null list");
                return null;
            }
            _logger.LogInformation("ReadList. Count:{Count}", list.Count);
            return list;
        }

        public StudentGroupViewModel? ReadElement(StudentGroupSearchModel model)
        {
            if (model == null) throw new ArgumentNullException(nameof(model));
            _logger.LogInformation("ReadElement. Id:{Id}", model.Id);
            var element = _StudentGroupStorage.GetElement(model);
            if (element == null)
            {
                _logger.LogWarning("ReadElement element not found");
                return null;
            }
            _logger.LogInformation("ReadElement find. Id:{Id}", element.Id);
            return element;
        }

        public bool Create(StudentGroupBindingModel model)
        {
            CheckModel(model);
            if (_StudentGroupStorage.Insert(model) == null)
            {
                _logger.LogWarning("Insert operation failed");
                return false;
            }
            return true;
        }

        public bool Update(StudentGroupBindingModel model)
        {
            CheckModel(model);
            if (_StudentGroupStorage.Update(model) == null)
            {
                _logger.LogWarning("Update operation failed");
                return false;
            }
            return true;
        }

        public bool Delete(StudentGroupBindingModel model)
        {
            CheckModel(model, false);
            _logger.LogInformation("Delete. Id:{Id}", model.Id);
            if (_StudentGroupStorage.Delete(model) == null)
            {
                _logger.LogWarning("Delete operation failed");
                return false;
            }
            return true;
        }

        private void CheckModel(StudentGroupBindingModel model, bool withParams = true)
        {
            if (model == null) throw new ArgumentNullException(nameof(model));
            if (!withParams) return;
            if (string.IsNullOrEmpty(model.GroupName))
                throw new ArgumentNullException("", nameof(model.GroupName));
            if (model.EducationDirectionId <= 0)
                throw new ArgumentNullException("", nameof(model.EducationDirectionId));
            if (model.CuratorId <= 0)
                throw new ArgumentNullException("", nameof(model.CuratorId));
            var element = _StudentGroupStorage.GetElement(new StudentGroupSearchModel
            {
                GroupName = model.GroupName
            });
            if (element != null && element.Id != model.Id)
                throw new InvalidOperationException("");
        }
    }
}
