// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.Extensions.Logging;
using DepartmentContracts.BindingModels;
using DepartmentContracts.BusinessLogicsContracts;
using DepartmentContracts.SearchModels;
using DepartmentContracts.StoragesContracts;
using DepartmentContracts.ViewModels;

namespace DepartmentBusinessLogic.BusinessLogics
{
    public class StudentOrderBlockLogic : IStudentOrderBlockLogic
    {
        private readonly ILogger _logger;

        private readonly IStudentOrderBlockStorage _StudentOrderBlockStorage;

        public StudentOrderBlockLogic(ILogger<StudentOrderBlockLogic> logger, IStudentOrderBlockStorage StudentOrderBlockStorage)
        {
            _logger = logger;
            _StudentOrderBlockStorage = StudentOrderBlockStorage;
        }

        public List<StudentOrderBlockViewModel>? ReadList(StudentOrderBlockSearchModel? model)
        {
            _logger.LogInformation("ReadList. Id:{Id}", model?.Id);
            var list = model == null ? _StudentOrderBlockStorage.GetFullList() : _StudentOrderBlockStorage.GetFilteredList(model);
            if (list == null)
            {
                _logger.LogWarning("ReadList return null list");
                return null;
            }
            _logger.LogInformation("ReadList. Count:{Count}", list.Count);
            return list;
        }

        public StudentOrderBlockViewModel? ReadElement(StudentOrderBlockSearchModel model)
        {
            if (model == null) throw new ArgumentNullException(nameof(model));
            _logger.LogInformation("ReadElement. Id:{Id}", model.Id);
            var element = _StudentOrderBlockStorage.GetElement(model);
            if (element == null)
            {
                _logger.LogWarning("ReadElement element not found");
                return null;
            }
            _logger.LogInformation("ReadElement find. Id:{Id}", element.Id);
            return element;
        }

        public bool Create(StudentOrderBlockBindingModel model)
        {
            CheckModel(model);
            if (_StudentOrderBlockStorage.Insert(model) == null)
            {
                _logger.LogWarning("Insert operation failed");
                return false;
            }
            return true;
        }

        public bool Update(StudentOrderBlockBindingModel model)
        {
            CheckModel(model);
            if (_StudentOrderBlockStorage.Update(model) == null)
            {
                _logger.LogWarning("Update operation failed");
                return false;
            }
            return true;
        }

        public bool Delete(StudentOrderBlockBindingModel model)
        {
            CheckModel(model, false);
            _logger.LogInformation("Delete. Id:{Id}", model.Id);
            if (_StudentOrderBlockStorage.Delete(model) == null)
            {
                _logger.LogWarning("Delete operation failed");
                return false;
            }
            return true;
        }

        private void CheckModel(StudentOrderBlockBindingModel model, bool withParams = true)
        {
            if (model == null) throw new ArgumentNullException(nameof(model));
            if (!withParams) return;
            if (model.StudentOrderId <= 0)
                throw new ArgumentNullException("", nameof(model.StudentOrderId));
            if (model.EducationDirectionId <= 0)
                throw new ArgumentNullException("", nameof(model.EducationDirectionId));
        }
    }
}
