// <auto-generated />
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using DepartmentContracts.BindingModels;
using DepartmentContracts.SearchModels;
using DepartmentContracts.StoragesContracts;
using DepartmentContracts.ViewModels;
using DepartmentDatabaseImplement.Models;

namespace DepartmentDatabaseImplement.Implements
{
    public class AcademicPlanStorage : IAcademicPlanStorage
    {
        public List<AcademicPlanViewModel> GetFullList()
        {
            using var context = new DepartmentDatabase();
            var query = context.Set<AcademicPlan>().AsQueryable();
            query = query.Include(x => x.EducationDirection);
            return query
                .ToList()
                .Select(x => MapToViewModel(x))
                .ToList();
        }

        public List<AcademicPlanViewModel> GetFilteredList(AcademicPlanSearchModel model)
        {
            using var context = new DepartmentDatabase();
            var query = context.Set<AcademicPlan>().AsQueryable();
            query = query.Include(x => x.EducationDirection);
            return query
                .ToList()
                .Select(x => MapToViewModel(x))
                .ToList();
        }

        public AcademicPlanViewModel? GetElement(AcademicPlanSearchModel model)
        {
            if (model == null) return null;
            using var context = new DepartmentDatabase();
            var query = context.Set<AcademicPlan>().AsQueryable();
            query = query.Include(x => x.EducationDirection);
            return query
                .FirstOrDefault(x => (model.Id.HasValue && x.Id == model.Id))
                is null ? null : MapToViewModel(query.FirstOrDefault(x => (model.Id.HasValue && x.Id == model.Id))!);
        }

        public AcademicPlanViewModel? Insert(AcademicPlanBindingModel model)
        {
            var newElement = AcademicPlan.Create(model);
            if (newElement == null) return null;
            using var context = new DepartmentDatabase();
            context.Set<AcademicPlan>().Add(newElement);
            context.SaveChanges();
            var saved = context.Set<AcademicPlan>()
                .Include(x => x.EducationDirection)
                .FirstOrDefault(x => x.Id == newElement.Id);
            return saved == null ? null : MapToViewModel(saved);
        }

        public AcademicPlanViewModel? Update(AcademicPlanBindingModel model)
        {
            using var context = new DepartmentDatabase();
            var element = context.Set<AcademicPlan>().AsQueryable();
            element = element.Include(x => x.EducationDirection);
            var dbElement = element.FirstOrDefault(x => x.Id == model.Id);
            if (dbElement == null) return null;
            dbElement.Update(model);
            context.SaveChanges();
            context.Entry(dbElement).Reload();
            context.Entry(dbElement).Reference(x => x.EducationDirection).Load();
            return MapToViewModel(dbElement);
        }

        public AcademicPlanViewModel? Delete(AcademicPlanBindingModel model)
        {
            using var context = new DepartmentDatabase();
            var element = context.Set<AcademicPlan>().AsQueryable();
            element = element.Include(x => x.EducationDirection);
            var dbElement = element.FirstOrDefault(x => x.Id == model.Id);
            if (dbElement == null) return null;
            context.Set<AcademicPlan>().Remove(dbElement);
            context.SaveChanges();
            return MapToViewModel(dbElement);
        }

        private static AcademicPlanViewModel MapToViewModel(AcademicPlan entity)
        {
            var vm = entity.GetViewModel;
            vm.EducationDirection = entity.EducationDirection == null ? string.Empty : entity.EducationDirection.Title;
            return vm;
        }
    }
}
