// <auto-generated />
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using DepartmentContracts.BindingModels;
using DepartmentContracts.SearchModels;
using DepartmentContracts.StoragesContracts;
using DepartmentContracts.ViewModels;
using DepartmentDatabaseImplement.Models;

namespace DepartmentDatabaseImplement.Implements
{
    public class AcademicPlanRecordStorage : IAcademicPlanRecordStorage
    {
        public List<AcademicPlanRecordViewModel> GetFullList()
        {
            using var context = new DepartmentDatabase();
            var query = context.Set<AcademicPlanRecord>().AsQueryable();
            query = query.Include(x => x.AcademicPlan);
            query = query.Include(x => x.Discipline);
            return query
                .ToList()
                .Select(x => MapToViewModel(x))
                .ToList();
        }

        public List<AcademicPlanRecordViewModel> GetFilteredList(AcademicPlanRecordSearchModel model)
        {
            using var context = new DepartmentDatabase();
            var query = context.Set<AcademicPlanRecord>().AsQueryable();
            query = query.Include(x => x.AcademicPlan);
            query = query.Include(x => x.Discipline);
            return query
                .ToList()
                .Select(x => MapToViewModel(x))
                .ToList();
        }

        public AcademicPlanRecordViewModel? GetElement(AcademicPlanRecordSearchModel model)
        {
            if (model == null) return null;
            using var context = new DepartmentDatabase();
            var query = context.Set<AcademicPlanRecord>().AsQueryable();
            query = query.Include(x => x.AcademicPlan);
            query = query.Include(x => x.Discipline);
            return query
                .FirstOrDefault(x => (model.Id.HasValue && x.Id == model.Id))
                is null ? null : MapToViewModel(query.FirstOrDefault(x => (model.Id.HasValue && x.Id == model.Id))!);
        }

        public AcademicPlanRecordViewModel? Insert(AcademicPlanRecordBindingModel model)
        {
            var newElement = AcademicPlanRecord.Create(model);
            if (newElement == null) return null;
            using var context = new DepartmentDatabase();
            context.Set<AcademicPlanRecord>().Add(newElement);
            context.SaveChanges();
            var saved = context.Set<AcademicPlanRecord>()
                .Include(x => x.AcademicPlan)
                .Include(x => x.Discipline)
                .FirstOrDefault(x => x.Id == newElement.Id);
            return saved == null ? null : MapToViewModel(saved);
        }

        public AcademicPlanRecordViewModel? Update(AcademicPlanRecordBindingModel model)
        {
            using var context = new DepartmentDatabase();
            var element = context.Set<AcademicPlanRecord>().AsQueryable();
            element = element.Include(x => x.AcademicPlan);
            element = element.Include(x => x.Discipline);
            var dbElement = element.FirstOrDefault(x => x.Id == model.Id);
            if (dbElement == null) return null;
            dbElement.Update(model);
            context.SaveChanges();
            context.Entry(dbElement).Reload();
            context.Entry(dbElement).Reference(x => x.AcademicPlan).Load();
            context.Entry(dbElement).Reference(x => x.Discipline).Load();
            return MapToViewModel(dbElement);
        }

        public AcademicPlanRecordViewModel? Delete(AcademicPlanRecordBindingModel model)
        {
            using var context = new DepartmentDatabase();
            var element = context.Set<AcademicPlanRecord>().AsQueryable();
            element = element.Include(x => x.AcademicPlan);
            element = element.Include(x => x.Discipline);
            var dbElement = element.FirstOrDefault(x => x.Id == model.Id);
            if (dbElement == null) return null;
            context.Set<AcademicPlanRecord>().Remove(dbElement);
            context.SaveChanges();
            return MapToViewModel(dbElement);
        }

        private static AcademicPlanRecordViewModel MapToViewModel(AcademicPlanRecord entity)
        {
            var vm = entity.GetViewModel;
            vm.AcademicPlan = entity.AcademicPlan == null ? string.Empty : entity.AcademicPlan.Id.ToString();
            vm.Name = entity.Discipline == null ? entity.Name : entity.Discipline.DisciplineName;
            return vm;
        }
    }
}


