// <auto-generated />
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using DepartmentContracts.BindingModels;
using DepartmentContracts.SearchModels;
using DepartmentContracts.StoragesContracts;
using DepartmentContracts.ViewModels;
using DepartmentDatabaseImplement.Models;

namespace DepartmentDatabaseImplement.Implements
{
    public class ClassroomStorage : IClassroomStorage
    {
        public List<ClassroomViewModel> GetFullList()
        {
            using var context = new DepartmentDatabase();
            var query = context.Set<Classroom>().AsQueryable();
            return query
                .ToList()
                .Select(x => MapToViewModel(x))
                .ToList();
        }

        public List<ClassroomViewModel> GetFilteredList(ClassroomSearchModel model)
        {
            if (string.IsNullOrEmpty(model.Number))
            {
                return new();
            }
            using var context = new DepartmentDatabase();
            var query = context.Set<Classroom>().AsQueryable();
            query = query.Where(x => x.Number.Contains(model.Number!));
            return query
                .ToList()
                .Select(x => MapToViewModel(x))
                .ToList();
        }

        public ClassroomViewModel? GetElement(ClassroomSearchModel model)
        {
            if (model == null) return null;
            using var context = new DepartmentDatabase();
            var query = context.Set<Classroom>().AsQueryable();
            return query
                .FirstOrDefault(x => (!string.IsNullOrEmpty(model.Number) && x.Number == model.Number) || (model.Id.HasValue && x.Id == model.Id))
                is null ? null : MapToViewModel(query.FirstOrDefault(x => (!string.IsNullOrEmpty(model.Number) && x.Number == model.Number) || (model.Id.HasValue && x.Id == model.Id))!);
        }

        public ClassroomViewModel? Insert(ClassroomBindingModel model)
        {
            var newElement = Classroom.Create(model);
            if (newElement == null) return null;
            using var context = new DepartmentDatabase();
            context.Set<Classroom>().Add(newElement);
            context.SaveChanges();
            return MapToViewModel(newElement);
        }

        public ClassroomViewModel? Update(ClassroomBindingModel model)
        {
            using var context = new DepartmentDatabase();
            var element = context.Set<Classroom>().AsQueryable();
            var dbElement = element.FirstOrDefault(x => x.Id == model.Id);
            if (dbElement == null) return null;
            dbElement.Update(model);
            context.SaveChanges();
            return MapToViewModel(dbElement);
        }

        public ClassroomViewModel? Delete(ClassroomBindingModel model)
        {
            using var context = new DepartmentDatabase();
            var element = context.Set<Classroom>().AsQueryable();
            var dbElement = element.FirstOrDefault(x => x.Id == model.Id);
            if (dbElement == null) return null;
            context.Set<Classroom>().Remove(dbElement);
            context.SaveChanges();
            return MapToViewModel(dbElement);
        }

        private static ClassroomViewModel MapToViewModel(Classroom entity)
        {
            var vm = entity.GetViewModel;
            return vm;
        }
    }
}
