// <auto-generated />
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using DepartmentContracts.BindingModels;
using DepartmentContracts.SearchModels;
using DepartmentContracts.StoragesContracts;
using DepartmentContracts.ViewModels;
using DepartmentDatabaseImplement.Models;

namespace DepartmentDatabaseImplement.Implements
{
    public class DisciplineBlockStorage : IDisciplineBlockStorage
    {
        public List<DisciplineBlockViewModel> GetFullList()
        {
            using var context = new DepartmentDatabase();
            var query = context.Set<DisciplineBlock>().AsQueryable();
            return query
                .ToList()
                .Select(x => MapToViewModel(x))
                .ToList();
        }

        public List<DisciplineBlockViewModel> GetFilteredList(DisciplineBlockSearchModel model)
        {
            if (string.IsNullOrEmpty(model.Title))
            {
                return new();
            }
            using var context = new DepartmentDatabase();
            var query = context.Set<DisciplineBlock>().AsQueryable();
            query = query.Where(x => x.Title.Contains(model.Title!));
            return query
                .ToList()
                .Select(x => MapToViewModel(x))
                .ToList();
        }

        public DisciplineBlockViewModel? GetElement(DisciplineBlockSearchModel model)
        {
            if (model == null) return null;
            using var context = new DepartmentDatabase();
            var query = context.Set<DisciplineBlock>().AsQueryable();
            return query
                .FirstOrDefault(x => (!string.IsNullOrEmpty(model.Title) && x.Title == model.Title) || (model.Id.HasValue && x.Id == model.Id))
                is null ? null : MapToViewModel(query.FirstOrDefault(x => (!string.IsNullOrEmpty(model.Title) && x.Title == model.Title) || (model.Id.HasValue && x.Id == model.Id))!);
        }

        public DisciplineBlockViewModel? Insert(DisciplineBlockBindingModel model)
        {
            var newElement = DisciplineBlock.Create(model);
            if (newElement == null) return null;
            using var context = new DepartmentDatabase();
            context.Set<DisciplineBlock>().Add(newElement);
            context.SaveChanges();
            return MapToViewModel(newElement);
        }

        public DisciplineBlockViewModel? Update(DisciplineBlockBindingModel model)
        {
            using var context = new DepartmentDatabase();
            var element = context.Set<DisciplineBlock>().AsQueryable();
            var dbElement = element.FirstOrDefault(x => x.Id == model.Id);
            if (dbElement == null) return null;
            dbElement.Update(model);
            context.SaveChanges();
            return MapToViewModel(dbElement);
        }

        public DisciplineBlockViewModel? Delete(DisciplineBlockBindingModel model)
        {
            using var context = new DepartmentDatabase();
            var element = context.Set<DisciplineBlock>().AsQueryable();
            var dbElement = element.FirstOrDefault(x => x.Id == model.Id);
            if (dbElement == null) return null;
            context.Set<DisciplineBlock>().Remove(dbElement);
            context.SaveChanges();
            return MapToViewModel(dbElement);
        }

        private static DisciplineBlockViewModel MapToViewModel(DisciplineBlock entity)
        {
            var vm = entity.GetViewModel;
            return vm;
        }
    }
}
