// <auto-generated />
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using DepartmentContracts.BindingModels;
using DepartmentContracts.SearchModels;
using DepartmentContracts.StoragesContracts;
using DepartmentContracts.ViewModels;
using DepartmentDatabaseImplement.Models;

namespace DepartmentDatabaseImplement.Implements
{
    public class DisciplineStudentRecordStorage : IDisciplineStudentRecordStorage
    {
        public List<DisciplineStudentRecordViewModel> GetFullList()
        {
            using var context = new DepartmentDatabase();
            var query = context.Set<DisciplineStudentRecord>().AsQueryable();
            query = query.Include(x => x.Discipline);
            query = query.Include(x => x.Student);
            return query
                .ToList()
                .Select(x => MapToViewModel(x))
                .ToList();
        }

        public List<DisciplineStudentRecordViewModel> GetFilteredList(DisciplineStudentRecordSearchModel model)
        {
            using var context = new DepartmentDatabase();
            var query = context.Set<DisciplineStudentRecord>().AsQueryable();
            query = query.Include(x => x.Discipline);
            query = query.Include(x => x.Student);
            return query
                .ToList()
                .Select(x => MapToViewModel(x))
                .ToList();
        }

        public DisciplineStudentRecordViewModel? GetElement(DisciplineStudentRecordSearchModel model)
        {
            if (model == null) return null;
            using var context = new DepartmentDatabase();
            var query = context.Set<DisciplineStudentRecord>().AsQueryable();
            query = query.Include(x => x.Discipline);
            query = query.Include(x => x.Student);
            return query
                .FirstOrDefault(x => (model.Id.HasValue && x.Id == model.Id))
                is null ? null : MapToViewModel(query.FirstOrDefault(x => (model.Id.HasValue && x.Id == model.Id))!);
        }

        public DisciplineStudentRecordViewModel? Insert(DisciplineStudentRecordBindingModel model)
        {
            var newElement = DisciplineStudentRecord.Create(model);
            if (newElement == null) return null;
            using var context = new DepartmentDatabase();
            context.Set<DisciplineStudentRecord>().Add(newElement);
            context.SaveChanges();
            var saved = context.Set<DisciplineStudentRecord>()
                .Include(x => x.Discipline)
                .Include(x => x.Student)
                .FirstOrDefault(x => x.Id == newElement.Id);
            return saved == null ? null : MapToViewModel(saved);
        }

        public DisciplineStudentRecordViewModel? Update(DisciplineStudentRecordBindingModel model)
        {
            using var context = new DepartmentDatabase();
            var element = context.Set<DisciplineStudentRecord>().AsQueryable();
            element = element.Include(x => x.Discipline);
            element = element.Include(x => x.Student);
            var dbElement = element.FirstOrDefault(x => x.Id == model.Id);
            if (dbElement == null) return null;
            dbElement.Update(model);
            context.SaveChanges();
            context.Entry(dbElement).Reload();
            context.Entry(dbElement).Reference(x => x.Discipline).Load();
            context.Entry(dbElement).Reference(x => x.Student).Load();
            return MapToViewModel(dbElement);
        }

        public DisciplineStudentRecordViewModel? Delete(DisciplineStudentRecordBindingModel model)
        {
            using var context = new DepartmentDatabase();
            var element = context.Set<DisciplineStudentRecord>().AsQueryable();
            element = element.Include(x => x.Discipline);
            element = element.Include(x => x.Student);
            var dbElement = element.FirstOrDefault(x => x.Id == model.Id);
            if (dbElement == null) return null;
            context.Set<DisciplineStudentRecord>().Remove(dbElement);
            context.SaveChanges();
            return MapToViewModel(dbElement);
        }

        private static DisciplineStudentRecordViewModel MapToViewModel(DisciplineStudentRecord entity)
        {
            var vm = entity.GetViewModel;
            vm.Discipline = entity.Discipline == null ? string.Empty : entity.Discipline.DisciplineName;
            vm.Student = entity.Student == null ? string.Empty : entity.Student.LastName;
            return vm;
        }
    }
}
