// <auto-generated />
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using DepartmentContracts.BindingModels;
using DepartmentContracts.SearchModels;
using DepartmentContracts.StoragesContracts;
using DepartmentContracts.ViewModels;
using DepartmentDatabaseImplement.Models;

namespace DepartmentDatabaseImplement.Implements
{
    public class DisciplineStorage : IDisciplineStorage
    {
        public List<DisciplineViewModel> GetFullList()
        {
            using var context = new DepartmentDatabase();
            var query = context.Set<Discipline>().AsQueryable();
            query = query.Include(x => x.DisciplineBlock);
            return query
                .ToList()
                .Select(x => MapToViewModel(x))
                .ToList();
        }

        public List<DisciplineViewModel> GetFilteredList(DisciplineSearchModel model)
        {
            if (string.IsNullOrEmpty(model.DisciplineName))
            {
                return new();
            }
            using var context = new DepartmentDatabase();
            var query = context.Set<Discipline>().AsQueryable();
            query = query.Include(x => x.DisciplineBlock);
            query = query.Where(x => x.DisciplineName.Contains(model.DisciplineName!));
            return query
                .ToList()
                .Select(x => MapToViewModel(x))
                .ToList();
        }

        public DisciplineViewModel? GetElement(DisciplineSearchModel model)
        {
            if (model == null) return null;
            using var context = new DepartmentDatabase();
            var query = context.Set<Discipline>().AsQueryable();
            query = query.Include(x => x.DisciplineBlock);
            return query
                .FirstOrDefault(x => (!string.IsNullOrEmpty(model.DisciplineName) && x.DisciplineName == model.DisciplineName) || (model.Id.HasValue && x.Id == model.Id))
                is null ? null : MapToViewModel(query.FirstOrDefault(x => (!string.IsNullOrEmpty(model.DisciplineName) && x.DisciplineName == model.DisciplineName) || (model.Id.HasValue && x.Id == model.Id))!);
        }

        public DisciplineViewModel? Insert(DisciplineBindingModel model)
        {
            var newElement = Discipline.Create(model);
            if (newElement == null) return null;
            using var context = new DepartmentDatabase();
            context.Set<Discipline>().Add(newElement);
            context.SaveChanges();
            var saved = context.Set<Discipline>()
                .Include(x => x.DisciplineBlock)
                .FirstOrDefault(x => x.Id == newElement.Id);
            return saved == null ? null : MapToViewModel(saved);
        }

        public DisciplineViewModel? Update(DisciplineBindingModel model)
        {
            using var context = new DepartmentDatabase();
            var element = context.Set<Discipline>().AsQueryable();
            element = element.Include(x => x.DisciplineBlock);
            var dbElement = element.FirstOrDefault(x => x.Id == model.Id);
            if (dbElement == null) return null;
            dbElement.Update(model);
            context.SaveChanges();
            context.Entry(dbElement).Reload();
            context.Entry(dbElement).Reference(x => x.DisciplineBlock).Load();
            return MapToViewModel(dbElement);
        }

        public DisciplineViewModel? Delete(DisciplineBindingModel model)
        {
            using var context = new DepartmentDatabase();
            var element = context.Set<Discipline>().AsQueryable();
            element = element.Include(x => x.DisciplineBlock);
            var dbElement = element.FirstOrDefault(x => x.Id == model.Id);
            if (dbElement == null) return null;
            context.Set<Discipline>().Remove(dbElement);
            context.SaveChanges();
            return MapToViewModel(dbElement);
        }

        private static DisciplineViewModel MapToViewModel(Discipline entity)
        {
            var vm = entity.GetViewModel;
            vm.DisciplineBlock = entity.DisciplineBlock == null ? string.Empty : entity.DisciplineBlock.Title;
            return vm;
        }
    }
}
