// <auto-generated />
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using DepartmentContracts.BindingModels;
using DepartmentContracts.SearchModels;
using DepartmentContracts.StoragesContracts;
using DepartmentContracts.ViewModels;
using DepartmentDatabaseImplement.Models;

namespace DepartmentDatabaseImplement.Implements
{
    public class EducationDirectionStorage : IEducationDirectionStorage
    {
        public List<EducationDirectionViewModel> GetFullList()
        {
            using var context = new DepartmentDatabase();
            var query = context.Set<EducationDirection>().AsQueryable();
            return query
                .ToList()
                .Select(x => MapToViewModel(x))
                .ToList();
        }

        public List<EducationDirectionViewModel> GetFilteredList(EducationDirectionSearchModel model)
        {
            if (string.IsNullOrEmpty(model.ShortName))
            {
                return new();
            }
            using var context = new DepartmentDatabase();
            var query = context.Set<EducationDirection>().AsQueryable();
            query = query.Where(x => x.ShortName.Contains(model.ShortName!));
            return query
                .ToList()
                .Select(x => MapToViewModel(x))
                .ToList();
        }

        public EducationDirectionViewModel? GetElement(EducationDirectionSearchModel model)
        {
            if (model == null) return null;
            using var context = new DepartmentDatabase();
            var query = context.Set<EducationDirection>().AsQueryable();
            return query
                .FirstOrDefault(x => (!string.IsNullOrEmpty(model.ShortName) && x.ShortName == model.ShortName) || (model.Id.HasValue && x.Id == model.Id))
                is null ? null : MapToViewModel(query.FirstOrDefault(x => (!string.IsNullOrEmpty(model.ShortName) && x.ShortName == model.ShortName) || (model.Id.HasValue && x.Id == model.Id))!);
        }

        public EducationDirectionViewModel? Insert(EducationDirectionBindingModel model)
        {
            var newElement = EducationDirection.Create(model);
            if (newElement == null) return null;
            using var context = new DepartmentDatabase();
            context.Set<EducationDirection>().Add(newElement);
            context.SaveChanges();
            return MapToViewModel(newElement);
        }

        public EducationDirectionViewModel? Update(EducationDirectionBindingModel model)
        {
            using var context = new DepartmentDatabase();
            var element = context.Set<EducationDirection>().AsQueryable();
            var dbElement = element.FirstOrDefault(x => x.Id == model.Id);
            if (dbElement == null) return null;
            dbElement.Update(model);
            context.SaveChanges();
            return MapToViewModel(dbElement);
        }

        public EducationDirectionViewModel? Delete(EducationDirectionBindingModel model)
        {
            using var context = new DepartmentDatabase();
            var element = context.Set<EducationDirection>().AsQueryable();
            var dbElement = element.FirstOrDefault(x => x.Id == model.Id);
            if (dbElement == null) return null;
            context.Set<EducationDirection>().Remove(dbElement);
            context.SaveChanges();
            return MapToViewModel(dbElement);
        }

        private static EducationDirectionViewModel MapToViewModel(EducationDirection entity)
        {
            var vm = entity.GetViewModel;
            return vm;
        }
    }
}
