// <auto-generated />
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using DepartmentContracts.BindingModels;
using DepartmentContracts.SearchModels;
using DepartmentContracts.StoragesContracts;
using DepartmentContracts.ViewModels;
using DepartmentDatabaseImplement.Models;

namespace DepartmentDatabaseImplement.Implements
{
    public class LecturerDepartmentPostStorage : ILecturerDepartmentPostStorage
    {
        public List<LecturerDepartmentPostViewModel> GetFullList()
        {
            using var context = new DepartmentDatabase();
            var query = context.Set<LecturerDepartmentPost>().AsQueryable();
            return query
                .ToList()
                .Select(x => MapToViewModel(x))
                .ToList();
        }

        public List<LecturerDepartmentPostViewModel> GetFilteredList(LecturerDepartmentPostSearchModel model)
        {
            using var context = new DepartmentDatabase();
            var query = context.Set<LecturerDepartmentPost>().AsQueryable();
            return query
                .ToList()
                .Select(x => MapToViewModel(x))
                .ToList();
        }

        public LecturerDepartmentPostViewModel? GetElement(LecturerDepartmentPostSearchModel model)
        {
            if (model == null) return null;
            using var context = new DepartmentDatabase();
            var query = context.Set<LecturerDepartmentPost>().AsQueryable();
            return query
                .FirstOrDefault(x => (model.Id.HasValue && x.Id == model.Id))
                is null ? null : MapToViewModel(query.FirstOrDefault(x => (model.Id.HasValue && x.Id == model.Id))!);
        }

        public LecturerDepartmentPostViewModel? Insert(LecturerDepartmentPostBindingModel model)
        {
            var newElement = LecturerDepartmentPost.Create(model);
            if (newElement == null) return null;
            using var context = new DepartmentDatabase();
            context.Set<LecturerDepartmentPost>().Add(newElement);
            context.SaveChanges();
            return MapToViewModel(newElement);
        }

        public LecturerDepartmentPostViewModel? Update(LecturerDepartmentPostBindingModel model)
        {
            using var context = new DepartmentDatabase();
            var element = context.Set<LecturerDepartmentPost>().AsQueryable();
            var dbElement = element.FirstOrDefault(x => x.Id == model.Id);
            if (dbElement == null) return null;
            dbElement.Update(model);
            context.SaveChanges();
            return MapToViewModel(dbElement);
        }

        public LecturerDepartmentPostViewModel? Delete(LecturerDepartmentPostBindingModel model)
        {
            using var context = new DepartmentDatabase();
            var element = context.Set<LecturerDepartmentPost>().AsQueryable();
            var dbElement = element.FirstOrDefault(x => x.Id == model.Id);
            if (dbElement == null) return null;
            context.Set<LecturerDepartmentPost>().Remove(dbElement);
            context.SaveChanges();
            return MapToViewModel(dbElement);
        }

        private static LecturerDepartmentPostViewModel MapToViewModel(LecturerDepartmentPost entity)
        {
            var vm = entity.GetViewModel;
            return vm;
        }
    }
}
