// <auto-generated />
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using DepartmentContracts.BindingModels;
using DepartmentContracts.SearchModels;
using DepartmentContracts.StoragesContracts;
using DepartmentContracts.ViewModels;
using DepartmentDatabaseImplement.Models;

namespace DepartmentDatabaseImplement.Implements
{
    public class LecturerStudyPostStorage : ILecturerStudyPostStorage
    {
        public List<LecturerStudyPostViewModel> GetFullList()
        {
            using var context = new DepartmentDatabase();
            var query = context.Set<LecturerStudyPost>().AsQueryable();
            return query
                .ToList()
                .Select(x => MapToViewModel(x))
                .ToList();
        }

        public List<LecturerStudyPostViewModel> GetFilteredList(LecturerStudyPostSearchModel model)
        {
            using var context = new DepartmentDatabase();
            var query = context.Set<LecturerStudyPost>().AsQueryable();
            return query
                .ToList()
                .Select(x => MapToViewModel(x))
                .ToList();
        }

        public LecturerStudyPostViewModel? GetElement(LecturerStudyPostSearchModel model)
        {
            if (model == null) return null;
            using var context = new DepartmentDatabase();
            var query = context.Set<LecturerStudyPost>().AsQueryable();
            return query
                .FirstOrDefault(x => (model.Id.HasValue && x.Id == model.Id))
                is null ? null : MapToViewModel(query.FirstOrDefault(x => (model.Id.HasValue && x.Id == model.Id))!);
        }

        public LecturerStudyPostViewModel? Insert(LecturerStudyPostBindingModel model)
        {
            var newElement = LecturerStudyPost.Create(model);
            if (newElement == null) return null;
            using var context = new DepartmentDatabase();
            context.Set<LecturerStudyPost>().Add(newElement);
            context.SaveChanges();
            return MapToViewModel(newElement);
        }

        public LecturerStudyPostViewModel? Update(LecturerStudyPostBindingModel model)
        {
            using var context = new DepartmentDatabase();
            var element = context.Set<LecturerStudyPost>().AsQueryable();
            var dbElement = element.FirstOrDefault(x => x.Id == model.Id);
            if (dbElement == null) return null;
            dbElement.Update(model);
            context.SaveChanges();
            return MapToViewModel(dbElement);
        }

        public LecturerStudyPostViewModel? Delete(LecturerStudyPostBindingModel model)
        {
            using var context = new DepartmentDatabase();
            var element = context.Set<LecturerStudyPost>().AsQueryable();
            var dbElement = element.FirstOrDefault(x => x.Id == model.Id);
            if (dbElement == null) return null;
            context.Set<LecturerStudyPost>().Remove(dbElement);
            context.SaveChanges();
            return MapToViewModel(dbElement);
        }

        private static LecturerStudyPostViewModel MapToViewModel(LecturerStudyPost entity)
        {
            var vm = entity.GetViewModel;
            return vm;
        }
    }
}
