// <auto-generated />
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using DepartmentContracts.BindingModels;
using DepartmentContracts.SearchModels;
using DepartmentContracts.StoragesContracts;
using DepartmentContracts.ViewModels;
using DepartmentDatabaseImplement.Models;

namespace DepartmentDatabaseImplement.Implements
{
    public class LecturerStorage : ILecturerStorage
    {
        public List<LecturerViewModel> GetFullList()
        {
            using var context = new DepartmentDatabase();
            var query = context.Set<Lecturer>().AsQueryable();
            query = query.Include(x => x.LecturerStudyPost);
            query = query.Include(x => x.LecturerDepartmentPost);
            return query
                .ToList()
                .Select(x => MapToViewModel(x))
                .ToList();
        }

        public List<LecturerViewModel> GetFilteredList(LecturerSearchModel model)
        {
            if (string.IsNullOrEmpty(model.FirstName))
            {
                return new();
            }
            using var context = new DepartmentDatabase();
            var query = context.Set<Lecturer>().AsQueryable();
            query = query.Include(x => x.LecturerStudyPost);
            query = query.Include(x => x.LecturerDepartmentPost);
            query = query.Where(x => x.FirstName.Contains(model.FirstName!));
            return query
                .ToList()
                .Select(x => MapToViewModel(x))
                .ToList();
        }

        public LecturerViewModel? GetElement(LecturerSearchModel model)
        {
            if (model == null) return null;
            using var context = new DepartmentDatabase();
            var query = context.Set<Lecturer>().AsQueryable();
            query = query.Include(x => x.LecturerStudyPost);
            query = query.Include(x => x.LecturerDepartmentPost);
            return query
                .FirstOrDefault(x => (!string.IsNullOrEmpty(model.FirstName) && x.FirstName == model.FirstName) || (model.Id.HasValue && x.Id == model.Id))
                is null ? null : MapToViewModel(query.FirstOrDefault(x => (!string.IsNullOrEmpty(model.FirstName) && x.FirstName == model.FirstName) || (model.Id.HasValue && x.Id == model.Id))!);
        }

        public LecturerViewModel? Insert(LecturerBindingModel model)
        {
            var newElement = Lecturer.Create(model);
            if (newElement == null) return null;
            using var context = new DepartmentDatabase();
            context.Set<Lecturer>().Add(newElement);
            context.SaveChanges();
            var saved = context.Set<Lecturer>()
                .Include(x => x.LecturerStudyPost)
                .Include(x => x.LecturerDepartmentPost)
                .FirstOrDefault(x => x.Id == newElement.Id);
            return saved == null ? null : MapToViewModel(saved);
        }

        public LecturerViewModel? Update(LecturerBindingModel model)
        {
            using var context = new DepartmentDatabase();
            var element = context.Set<Lecturer>().AsQueryable();
            element = element.Include(x => x.LecturerStudyPost);
            element = element.Include(x => x.LecturerDepartmentPost);
            var dbElement = element.FirstOrDefault(x => x.Id == model.Id);
            if (dbElement == null) return null;
            dbElement.Update(model);
            context.SaveChanges();
            context.Entry(dbElement).Reload();
            context.Entry(dbElement).Reference(x => x.LecturerStudyPost).Load();
            context.Entry(dbElement).Reference(x => x.LecturerDepartmentPost).Load();
            return MapToViewModel(dbElement);
        }

        public LecturerViewModel? Delete(LecturerBindingModel model)
        {
            using var context = new DepartmentDatabase();
            var element = context.Set<Lecturer>().AsQueryable();
            element = element.Include(x => x.LecturerStudyPost);
            element = element.Include(x => x.LecturerDepartmentPost);
            var dbElement = element.FirstOrDefault(x => x.Id == model.Id);
            if (dbElement == null) return null;
            context.Set<Lecturer>().Remove(dbElement);
            context.SaveChanges();
            return MapToViewModel(dbElement);
        }

        private static LecturerViewModel MapToViewModel(Lecturer entity)
        {
            var vm = entity.GetViewModel;
            vm.LecturerStudyPost = entity.LecturerStudyPost == null ? string.Empty : entity.LecturerStudyPost.StudyPostTitle;
            vm.LecturerDepartmentPost = entity.LecturerDepartmentPost == null ? string.Empty : entity.LecturerDepartmentPost.DepartmentPostTitle;
            return vm;
        }
    }
}
