// <auto-generated />
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using DepartmentContracts.BindingModels;
using DepartmentContracts.SearchModels;
using DepartmentContracts.StoragesContracts;
using DepartmentContracts.ViewModels;
using DepartmentDatabaseImplement.Models;

namespace DepartmentDatabaseImplement.Implements
{
    public class StudentStorage : IStudentStorage
    {
        public List<StudentViewModel> GetFullList()
        {
            using var context = new DepartmentDatabase();
            var query = context.Set<Student>().AsQueryable();
            query = query.Include(x => x.StudentGroup);
            return query
                .ToList()
                .Select(x => MapToViewModel(x))
                .ToList();
        }

        public List<StudentViewModel> GetFilteredList(StudentSearchModel model)
        {
            if (string.IsNullOrEmpty(model.FirstName))
            {
                return new();
            }
            using var context = new DepartmentDatabase();
            var query = context.Set<Student>().AsQueryable();
            query = query.Include(x => x.StudentGroup);
            query = query.Where(x => x.FirstName.Contains(model.FirstName!));
            return query
                .ToList()
                .Select(x => MapToViewModel(x))
                .ToList();
        }

        public StudentViewModel? GetElement(StudentSearchModel model)
        {
            if (model == null) return null;
            using var context = new DepartmentDatabase();
            var query = context.Set<Student>().AsQueryable();
            query = query.Include(x => x.StudentGroup);
            return query
                .FirstOrDefault(x => (!string.IsNullOrEmpty(model.FirstName) && x.FirstName == model.FirstName) || (model.Id.HasValue && x.Id == model.Id))
                is null ? null : MapToViewModel(query.FirstOrDefault(x => (!string.IsNullOrEmpty(model.FirstName) && x.FirstName == model.FirstName) || (model.Id.HasValue && x.Id == model.Id))!);
        }

        public StudentViewModel? Insert(StudentBindingModel model)
        {
            var newElement = Student.Create(model);
            if (newElement == null) return null;
            using var context = new DepartmentDatabase();
            context.Set<Student>().Add(newElement);
            context.SaveChanges();
            var saved = context.Set<Student>()
                .Include(x => x.StudentGroup)
                .FirstOrDefault(x => x.Id == newElement.Id);
            return saved == null ? null : MapToViewModel(saved);
        }

        public StudentViewModel? Update(StudentBindingModel model)
        {
            using var context = new DepartmentDatabase();
            var element = context.Set<Student>().AsQueryable();
            element = element.Include(x => x.StudentGroup);
            var dbElement = element.FirstOrDefault(x => x.Id == model.Id);
            if (dbElement == null) return null;
            dbElement.Update(model);
            context.SaveChanges();
            context.Entry(dbElement).Reload();
            context.Entry(dbElement).Reference(x => x.StudentGroup).Load();
            return MapToViewModel(dbElement);
        }

        public StudentViewModel? Delete(StudentBindingModel model)
        {
            using var context = new DepartmentDatabase();
            var element = context.Set<Student>().AsQueryable();
            element = element.Include(x => x.StudentGroup);
            var dbElement = element.FirstOrDefault(x => x.Id == model.Id);
            if (dbElement == null) return null;
            context.Set<Student>().Remove(dbElement);
            context.SaveChanges();
            return MapToViewModel(dbElement);
        }

        private static StudentViewModel MapToViewModel(Student entity)
        {
            var vm = entity.GetViewModel;
            vm.StudentGroup = entity.StudentGroup == null ? string.Empty : entity.StudentGroup.GroupName;
            return vm;
        }
    }
}
