// <auto-generated />
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using DepartmentContracts.BindingModels;
using DepartmentContracts.SearchModels;
using DepartmentContracts.StoragesContracts;
using DepartmentContracts.ViewModels;
using DepartmentDatabaseImplement.Models;

namespace DepartmentDatabaseImplement.Implements
{
    public class StudentOrderBlockStorage : IStudentOrderBlockStorage
    {
        public List<StudentOrderBlockViewModel> GetFullList()
        {
            using var context = new DepartmentDatabase();
            var query = context.Set<StudentOrderBlock>().AsQueryable();
            query = query.Include(x => x.StudentOrder);
            query = query.Include(x => x.EducationDirection);
            return query
                .ToList()
                .Select(x => MapToViewModel(x))
                .ToList();
        }

        public List<StudentOrderBlockViewModel> GetFilteredList(StudentOrderBlockSearchModel model)
        {
            using var context = new DepartmentDatabase();
            var query = context.Set<StudentOrderBlock>().AsQueryable();
            query = query.Include(x => x.StudentOrder);
            query = query.Include(x => x.EducationDirection);
            return query
                .ToList()
                .Select(x => MapToViewModel(x))
                .ToList();
        }

        public StudentOrderBlockViewModel? GetElement(StudentOrderBlockSearchModel model)
        {
            if (model == null) return null;
            using var context = new DepartmentDatabase();
            var query = context.Set<StudentOrderBlock>().AsQueryable();
            query = query.Include(x => x.StudentOrder);
            query = query.Include(x => x.EducationDirection);
            return query
                .FirstOrDefault(x => (model.Id.HasValue && x.Id == model.Id))
                is null ? null : MapToViewModel(query.FirstOrDefault(x => (model.Id.HasValue && x.Id == model.Id))!);
        }

        public StudentOrderBlockViewModel? Insert(StudentOrderBlockBindingModel model)
        {
            var newElement = StudentOrderBlock.Create(model);
            if (newElement == null) return null;
            using var context = new DepartmentDatabase();
            context.Set<StudentOrderBlock>().Add(newElement);
            context.SaveChanges();
            var saved = context.Set<StudentOrderBlock>()
                .Include(x => x.StudentOrder)
                .Include(x => x.EducationDirection)
                .FirstOrDefault(x => x.Id == newElement.Id);
            return saved == null ? null : MapToViewModel(saved);
        }

        public StudentOrderBlockViewModel? Update(StudentOrderBlockBindingModel model)
        {
            using var context = new DepartmentDatabase();
            var element = context.Set<StudentOrderBlock>().AsQueryable();
            element = element.Include(x => x.StudentOrder);
            element = element.Include(x => x.EducationDirection);
            var dbElement = element.FirstOrDefault(x => x.Id == model.Id);
            if (dbElement == null) return null;
            dbElement.Update(model);
            context.SaveChanges();
            context.Entry(dbElement).Reload();
            context.Entry(dbElement).Reference(x => x.StudentOrder).Load();
            context.Entry(dbElement).Reference(x => x.EducationDirection).Load();
            return MapToViewModel(dbElement);
        }

        public StudentOrderBlockViewModel? Delete(StudentOrderBlockBindingModel model)
        {
            using var context = new DepartmentDatabase();
            var element = context.Set<StudentOrderBlock>().AsQueryable();
            element = element.Include(x => x.StudentOrder);
            element = element.Include(x => x.EducationDirection);
            var dbElement = element.FirstOrDefault(x => x.Id == model.Id);
            if (dbElement == null) return null;
            context.Set<StudentOrderBlock>().Remove(dbElement);
            context.SaveChanges();
            return MapToViewModel(dbElement);
        }

        private static StudentOrderBlockViewModel MapToViewModel(StudentOrderBlock entity)
        {
            var vm = entity.GetViewModel;
            vm.StudentOrder = entity.StudentOrder == null ? string.Empty : entity.StudentOrder.OrderNumber;
            vm.EducationDirection = entity.EducationDirection == null ? string.Empty : entity.EducationDirection.Title;
            return vm;
        }
    }
}
