// <auto-generated />
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using DepartmentContracts.BindingModels;
using DepartmentContracts.SearchModels;
using DepartmentContracts.StoragesContracts;
using DepartmentContracts.ViewModels;
using DepartmentDatabaseImplement.Models;

namespace DepartmentDatabaseImplement.Implements
{
    public class StudentGroupStorage : IStudentGroupStorage
    {
        public List<StudentGroupViewModel> GetFullList()
        {
            using var context = new DepartmentDatabase();
            var query = context.Set<StudentGroup>().AsQueryable();
            query = query.Include(x => x.EducationDirection);
            query = query.Include(x => x.Curator);
            return query
                .ToList()
                .Select(x => MapToViewModel(x))
                .ToList();
        }

        public List<StudentGroupViewModel> GetFilteredList(StudentGroupSearchModel model)
        {
            if (string.IsNullOrEmpty(model.GroupName))
            {
                return new();
            }
            using var context = new DepartmentDatabase();
            var query = context.Set<StudentGroup>().AsQueryable();
            query = query.Include(x => x.EducationDirection);
            query = query.Include(x => x.Curator);
            query = query.Where(x => x.GroupName.Contains(model.GroupName!));
            return query
                .ToList()
                .Select(x => MapToViewModel(x))
                .ToList();
        }

        public StudentGroupViewModel? GetElement(StudentGroupSearchModel model)
        {
            if (model == null) return null;
            using var context = new DepartmentDatabase();
            var query = context.Set<StudentGroup>().AsQueryable();
            query = query.Include(x => x.EducationDirection);
            query = query.Include(x => x.Curator);
            return query
                .FirstOrDefault(x => (!string.IsNullOrEmpty(model.GroupName) && x.GroupName == model.GroupName) || (model.Id.HasValue && x.Id == model.Id))
                is null ? null : MapToViewModel(query.FirstOrDefault(x => (!string.IsNullOrEmpty(model.GroupName) && x.GroupName == model.GroupName) || (model.Id.HasValue && x.Id == model.Id))!);
        }

        public StudentGroupViewModel? Insert(StudentGroupBindingModel model)
        {
            var newElement = StudentGroup.Create(model);
            if (newElement == null) return null;
            using var context = new DepartmentDatabase();
            context.Set<StudentGroup>().Add(newElement);
            context.SaveChanges();
            var saved = context.Set<StudentGroup>()
                .Include(x => x.EducationDirection)
                .Include(x => x.Curator)
                .FirstOrDefault(x => x.Id == newElement.Id);
            return saved == null ? null : MapToViewModel(saved);
        }

        public StudentGroupViewModel? Update(StudentGroupBindingModel model)
        {
            using var context = new DepartmentDatabase();
            var element = context.Set<StudentGroup>().AsQueryable();
            element = element.Include(x => x.EducationDirection);
            element = element.Include(x => x.Curator);
            var dbElement = element.FirstOrDefault(x => x.Id == model.Id);
            if (dbElement == null) return null;
            dbElement.Update(model);
            context.SaveChanges();
            context.Entry(dbElement).Reload();
            context.Entry(dbElement).Reference(x => x.EducationDirection).Load();
            context.Entry(dbElement).Reference(x => x.Curator).Load();
            return MapToViewModel(dbElement);
        }

        public StudentGroupViewModel? Delete(StudentGroupBindingModel model)
        {
            using var context = new DepartmentDatabase();
            var element = context.Set<StudentGroup>().AsQueryable();
            element = element.Include(x => x.EducationDirection);
            element = element.Include(x => x.Curator);
            var dbElement = element.FirstOrDefault(x => x.Id == model.Id);
            if (dbElement == null) return null;
            context.Set<StudentGroup>().Remove(dbElement);
            context.SaveChanges();
            return MapToViewModel(dbElement);
        }

        private static StudentGroupViewModel MapToViewModel(StudentGroup entity)
        {
            var vm = entity.GetViewModel;
            vm.EducationDirection = entity.EducationDirection == null ? string.Empty : entity.EducationDirection.Title;
            vm.Curator = entity.Curator == null ? string.Empty : entity.Curator.LastName;
            return vm;
        }
    }
}
