// <auto-generated />
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using DepartmentContracts.BindingModels;
using DepartmentContracts.SearchModels;
using DepartmentContracts.StoragesContracts;
using DepartmentContracts.ViewModels;
using DepartmentDatabaseImplement.Models;

namespace DepartmentDatabaseImplement.Implements
{
    public class StudentOrderStorage : IStudentOrderStorage
    {
        public List<StudentOrderViewModel> GetFullList()
        {
            using var context = new DepartmentDatabase();
            var query = context.Set<StudentOrder>().AsQueryable();
            return query
                .ToList()
                .Select(x => MapToViewModel(x))
                .ToList();
        }

        public List<StudentOrderViewModel> GetFilteredList(StudentOrderSearchModel model)
        {
            using var context = new DepartmentDatabase();
            var query = context.Set<StudentOrder>().AsQueryable();
            return query
                .ToList()
                .Select(x => MapToViewModel(x))
                .ToList();
        }

        public StudentOrderViewModel? GetElement(StudentOrderSearchModel model)
        {
            if (model == null) return null;
            using var context = new DepartmentDatabase();
            var query = context.Set<StudentOrder>().AsQueryable();
            return query
                .FirstOrDefault(x => (model.Id.HasValue && x.Id == model.Id))
                is null ? null : MapToViewModel(query.FirstOrDefault(x => (model.Id.HasValue && x.Id == model.Id))!);
        }

        public StudentOrderViewModel? Insert(StudentOrderBindingModel model)
        {
            var newElement = StudentOrder.Create(model);
            if (newElement == null) return null;
            using var context = new DepartmentDatabase();
            context.Set<StudentOrder>().Add(newElement);
            context.SaveChanges();
            return MapToViewModel(newElement);
        }

        public StudentOrderViewModel? Update(StudentOrderBindingModel model)
        {
            using var context = new DepartmentDatabase();
            var element = context.Set<StudentOrder>().AsQueryable();
            var dbElement = element.FirstOrDefault(x => x.Id == model.Id);
            if (dbElement == null) return null;
            dbElement.Update(model);
            context.SaveChanges();
            return MapToViewModel(dbElement);
        }

        public StudentOrderViewModel? Delete(StudentOrderBindingModel model)
        {
            using var context = new DepartmentDatabase();
            var element = context.Set<StudentOrder>().AsQueryable();
            var dbElement = element.FirstOrDefault(x => x.Id == model.Id);
            if (dbElement == null) return null;
            context.Set<StudentOrder>().Remove(dbElement);
            context.SaveChanges();
            return MapToViewModel(dbElement);
        }

        private static StudentOrderViewModel MapToViewModel(StudentOrder entity)
        {
            var vm = entity.GetViewModel;
            return vm;
        }
    }
}
