// <auto-generated />

using System;
using DepartmentDataModels.Enums;

namespace DepartmentDataModels.Models
{
    public interface IAcademicPlanRecordModel : IId
    {
        int Id { get; }
        int AcademicPlanId { get; }
        int DisciplineId { get; }
        int? AcademicPlanRecordParentId { get; }
        bool InDepartment { get; }
        Semesters Semester { get; }
        int Zet { get; } // зетки для расчета часов
        bool IsParent { get; }
        bool IsChild { get; }
        bool IsFacultative { get; }
        bool IsUseInWorkload { get; }
        bool IsActiveSemester { get; }
    }
}
