// <auto-generated />

using System;
using DepartmentDataModels.Enums;

namespace DepartmentDataModels.Models
{
    public interface IAcademicPlanRecordModel : IId
    {
        int Id { get; }
        int AcademicPlanId { get; }
        string Index { get; }
        string Name { get; }
        int Semester { get; }
        int Zet { get; }
        int AcademicHours { get; }
        int? Exam { get; }
        int? Pass { get; }
        int? GradedPass { get; }
        int? CourseWork { get; }
        int? CourseProject { get; }
        int? Rgr { get; }
        int? Lectures { get; }
        int? LaboratoryHours { get; }
        int? PracticalHours { get; }


        int? DisciplineId { get; }
    }
}
