// <auto-generated />

using System;
using DepartmentDataModels.Enums;

namespace DepartmentDataModels.Models
{
    public interface IAcademicPlanModel : IId
    {
        int Id { get; }
        int? EducationDirectionId { get; }
        AcademicCourse AcademicCourses { get; }
        int Year { get; }
    }
}
