// <auto-generated />

using System;
using DepartmentDataModels.Enums;

namespace DepartmentDataModels.Models
{
    public interface IClassroomModel : IId
    {
        int Id { get; }
        string Number { get; }
        ClassroomTypes ClassroomType { get; }
        int Capacity { get; }
        bool NotUseInSchedule { get; }
    }
}
