// <auto-generated />

using System;

namespace DepartmentDataModels.Models
{
    public interface IDisciplineBlockModel : IId
    {
        int Id { get; }
        string Title { get; }
        string DisciplineBlockBlueAsteriskName { get; }
        bool DisciplineBlockUseForGrouping { get; }
        int DisciplineBlockOrder { get; }
    }
}
