// <auto-generated />

using System;

namespace DepartmentDataModels.Models
{
    public interface IDisciplineModel : IId
    {
        int Id { get; }
        int DisciplineBlockId { get; }
        string DisciplineName { get; }
        string DisciplineShortName { get; }
        string DisciplineDescription { get; }
        string DisciplineBlockBlueAsteriskName { get; }
    }
}
