// <auto-generated />

using System;

namespace DepartmentDataModels.Models
{
    public interface IDisciplineModel : IId
    {
        int Id { get; }
        int DisciplineBlockId { get; }
        string DisciplineName { get; }
        string DisciplineShortName { get; }
        string DisciplineDescription { get; }
        string DisciplineBlockBlueAsteriskName { get; }
        bool HasExam { get; }
        bool HasCredit { get; }
        bool HasCourseWork { get; }
        bool HasCourseProject { get; }
    }
}
