// <auto-generated />

using System;
using DepartmentDataModels.Enums;

namespace DepartmentDataModels.Models
{
    public interface IDisciplineStudentRecordModel : IId
    {
        int Id { get; }
        int DisciplineId { get; }
        int StudentId { get; }
        Semesters Semester { get; }
        string Variant { get; }
        int SubGroup { get; }
        MarkType MarkType { get; }
    }
}
