// <auto-generated />

using System;
using DepartmentDataModels.Enums;

namespace DepartmentDataModels.Models
{
    public interface IEducationDirectionModel : IId
    {
        int Id { get; }
        string Cipher { get; }
        string ShortName { get; }
        string Title { get; }
        EducationDirectionQualification Qualification { get; }
        string Profile { get; }
        string Description { get; }
    }
}
