// <auto-generated />

using System;

namespace DepartmentDataModels.Models
{
    public interface ILecturerStudyPostModel : IId
    {
        int Id { get; }
        string StudyPostTitle { get; }
        int Hours { get; }
    }
}
