// <auto-generated />

using System;
using DepartmentDataModels.Enums;

namespace DepartmentDataModels.Models
{
    public interface ILecturerModel : IId
    {
        int Id { get; }
        int? LecturerStudyPostId { get; }
        int LecturerDepartmentPostId { get; }
        string FirstName { get; }
        string LastName { get; }
        string Patronymic { get; }
        string Abbreviation { get; }
        DateTime DateBirth { get; }
        string Address { get; }
        string Email { get; }
        string MobileNumber { get; }
        string HomeNumber { get; }
        Rank Rank { get; }
        Rank2 Rank2 { get; }
        string Description { get; }
        byte[]? Photo { get; }
        bool OnlyForPrivate { get; }
    }
}
