// <auto-generated />

using System;

namespace DepartmentDataModels.Models
{
    public interface ILecturerDepartmentPostModel : IId
    {
        int Id { get; }
        string DepartmentPostTitle { get; }
        int Order { get; }
    }
}
