// <auto-generated />

using System;

namespace DepartmentDataModels.Models
{
    public interface IStudentOrderBlockStudentModel : IId
    {
        int Id { get; }
        int StudentOrderBlockId { get; }
        int StudentId { get; }
        int? StudentGroupFromId { get; }
        int? StudentGroupToId { get; }
    }
}
