// <auto-generated />

using System;
using DepartmentDataModels.Enums;

namespace DepartmentDataModels.Models
{
    public interface IStudentOrderModel : IId
    {
        int Id { get; }
        string OrderNumber { get; }
        StudentOrderType StudentOrderType { get; }
    }
}
