// <auto-generated />

using System;
using DepartmentDataModels.Enums;

namespace DepartmentDataModels.Models
{
    public interface IStudentGroupModel : IId
    {
        int Id { get; }
        int EducationDirectionId { get; }
        int? CuratorId { get; }
        string GroupName { get; }
        AcademicCourse Course { get; }
    }
}
