// <auto-generated />

using System;
using DepartmentDataModels.Enums;

namespace DepartmentDataModels.Models
{
    public interface IStudentModel : IId
    {
        int Id { get; }
        int? StudentGroupId { get; }
        string NumberOfBook { get; }
        string FirstName { get; }
        string LastName { get; }
        string Patronymic { get; }
        string Email { get; }
        StudentState StudentState { get; }
        string Description { get; }
        byte[]? Photo { get; }
        bool IsSteward { get; }
    }
}
