// <auto-generated />

using System;
using DepartmentDataModels.Enums;

namespace DepartmentDataModels.Models
{
    public interface IStudentOrderBlockModel : IId
    {
        int Id { get; }
        int StudentOrderId { get; }
        int EducationDirectionId { get; }
        StudentOrderType StudentOrderType { get; }
    }
}
