// <auto-generated />

using DepartmentDataModels.Enums;
using DepartmentDataModels.Models;
using DepartmentContracts.Attributes;

namespace DepartmentContracts.ViewModels
{
    public class AcademicPlanRecordViewModel : IAcademicPlanRecordModel
    {
        [Column(visible: false)]
        public int Id { get; set; }
        [Column(visible: false)]
        public int AcademicPlanId { get; set; }
        [Column(title: "", width: 100)]
        public string AcademicPlan { get; set; } = string.Empty;
        [Column(title: "", width: 100)]
        public string Index { get; set; } = string.Empty;
        [Column(title: "", width: 100)]
        public string Name { get; set; } = string.Empty;
        [Column(title: "", width: 100)]
        public bool InDepartment { get; set; }
        [Column(title: "", width: 100)]
        public int Semester { get; set; }
        [Column(title: "", width: 100)]
        public int Zet { get; set; }
        [Column(title: "", width: 100)]
        public int AcademicHours { get; set; }
        [Column(title: "", width: 100)]
        public int? Exam { get; set; }
        [Column(title: "", width: 100)]
        public int? Pass { get; set; }
        [Column(title: "", width: 100)]
        public int? GradedPass { get; set; }
        [Column(title: "", width: 100)]
        public int? CourseWork { get; set; }
        [Column(title: "", width: 100)]
        public int? CourseProject { get; set; }
        [Column(title: "", width: 100)]
        public int? Rgr { get; set; }
        [Column(title: "", width: 100)]
        public int? Lectures { get; set; }
        [Column(title: "", width: 100)]
        public int? LaboratoryHours { get; set; }
        [Column(title: "", width: 100)]
        public int? PracticalHours { get; set; }
        [Column(title: "", width: 100)]
        public bool IsParent { get; set; }
        [Column(title: "", width: 100)]
        public bool IsChild { get; set; }
        [Column(title: "", width: 100)]
        public bool IsFacultative { get; set; }
        [Column(title: "", width: 100)]
        public bool IsUseInWorkload { get; set; }
        [Column(title: "", width: 100)]
        public bool IsActiveSemester { get; set; }


        [Column(visible: false)]
        public int? DisciplineId { get; set; }
    }
}