// <auto-generated />

using DepartmentDataModels.Enums;
using DepartmentDataModels.Models;
using DepartmentContracts.Attributes;

namespace DepartmentContracts.ViewModels
{
    public class AcademicPlanViewModel : IAcademicPlanModel
    {
        [Column(visible: false)]
        public int Id { get; set; }
        [Column(visible: false)]
        public int? EducationDirectionId { get; set; }
        [Column(title: "", width: 100)]
        public string EducationDirection { get; set; } = string.Empty;
        [Column(title: "", width: 100)]
        public AcademicCourse AcademicCourses { get; set; }
        [Column(title: "", width: 100)]
        public EducationForm EducationForm { get; set; }
        [Column(title: "", width: 100)]
        public string Year { get; set; }
    }
}
