// <auto-generated />

using DepartmentDataModels.Enums;
using DepartmentDataModels.Models;
using DepartmentContracts.Attributes;

namespace DepartmentContracts.ViewModels
{
    public class AcademicPlanRecordViewModel : IAcademicPlanRecordModel
    {
        [Column(visible: false)]
        public int Id { get; set; }
        [Column(visible: false)]
        public int AcademicPlanId { get; set; }
        [Column(title: "", width: 100)]
        public string AcademicPlan { get; set; } = string.Empty;
        [Column(visible: false)]
        public int DisciplineId { get; set; }
        [Column(title: "", width: 100)]
        public string Discipline { get; set; } = string.Empty;
        [Column(visible: false)]
        public int? AcademicPlanRecordParentId { get; set; }
        [Column(title: "", width: 100)]
        public string AcademicPlanRecord { get; set; } = string.Empty;
        [Column(title: "", width: 100)]
        public bool InDepartment { get; set; }
        [Column(title: "", width: 100)]
        public Semesters Semester { get; set; }
        [Column(title: "", width: 100)]
        public int Zet { get; set; }
        [Column(title: "", width: 100)]
        public bool IsParent { get; set; }
        [Column(title: "", width: 100)]
        public bool IsChild { get; set; }
        [Column(title: "", width: 100)]
        public bool IsFacultative { get; set; }
        [Column(title: "", width: 100)]
        public bool IsUseInWorkload { get; set; }
        [Column(title: "", width: 100)]
        public bool IsActiveSemester { get; set; }
    }
}
