// <auto-generated />

using DepartmentDataModels.Enums;
using DepartmentDataModels.Models;
using DepartmentContracts.Attributes;

namespace DepartmentContracts.ViewModels
{
    public class ClassroomViewModel : IClassroomModel
    {
        [Column(visible: false)]
        public int Id { get; set; }
        [Column(title: "", width: 100)]
        public string Number { get; set; } = string.Empty;
        [Column(title: "", width: 100)]
        public ClassroomTypes Type { get; set; }
        [Column(title: "", width: 100)]
        public int Capacity { get; set; }
        [Column(title: "", width: 100)]
        public bool NotUseInSchedule { get; set; }
        [Column(title: "", width: 100)]
        public bool HasProjector { get; set; }
    }
}
