// <auto-generated />

using DepartmentDataModels.Models;
using DepartmentContracts.Attributes;

namespace DepartmentContracts.ViewModels
{
    public class DisciplineBlockViewModel : IDisciplineBlockModel
    {
        [Column(visible: false)]
        public int Id { get; set; }
        [Column(title: "", width: 100)]
        public string Title { get; set; } = string.Empty;
        [Column(title: "", width: 100)]
        public string DisciplineBlockBlueAsteriskName { get; set; } = string.Empty;
        [Column(title: "", width: 100)]
        public bool DisciplineBlockUseForGrouping { get; set; }
        [Column(title: "", width: 100)]
        public int DisciplineBlockOrder { get; set; }
    }
}
