// <auto-generated />

using DepartmentDataModels.Models;
using DepartmentContracts.Attributes;

namespace DepartmentContracts.ViewModels
{
    public class DisciplineViewModel : IDisciplineModel
    {
        [Column(visible: false)]
        public int Id { get; set; }
        [Column(visible: false)]
        public int DisciplineBlockId { get; set; }
        [Column(title: "", width: 100)]
        public string DisciplineBlock { get; set; } = string.Empty;
        [Column(title: "", width: 100)]
        public string DisciplineName { get; set; } = string.Empty;
        [Column(title: "", width: 100)]
        public string DisciplineShortName { get; set; } = string.Empty;
        [Column(title: "", width: 100)]
        public string DisciplineDescription { get; set; } = string.Empty;
        [Column(title: "", width: 100)]
        public string DisciplineBlockBlueAsteriskName { get; set; } = string.Empty;
        [Column(title: "", width: 100)]
        public bool HasExam { get; set; }
        [Column(title: "", width: 100)]
        public bool HasCredit { get; set; }
        [Column(title: "", width: 100)]
        public bool HasCourseWork { get; set; }
        [Column(title: "", width: 100)]
        public bool HasCourseProject { get; set; }
    }
}
