// <auto-generated />

using DepartmentDataModels.Enums;
using DepartmentDataModels.Models;
using DepartmentContracts.Attributes;

namespace DepartmentContracts.ViewModels
{
    public class EducationDirectionViewModel : IEducationDirectionModel
    {
        [Column(visible: false)]
        public int Id { get; set; }
        [Column(title: "", width: 100)]
        public string Cipher { get; set; } = string.Empty;
        [Column(title: "", width: 100)]
        public string ShortName { get; set; } = string.Empty;
        [Column(title: "", width: 100)]
        public string Title { get; set; } = string.Empty;
        [Column(title: "", width: 100)]
        public EducationDirectionQualification Qualification { get; set; }
        [Column(title: "", width: 100)]
        public string Profile { get; set; } = string.Empty;
        [Column(title: "", width: 100)]
        public string Description { get; set; } = string.Empty;
    }
}
