// <auto-generated />

using DepartmentDataModels.Models;
using DepartmentContracts.Attributes;

namespace DepartmentContracts.ViewModels
{
    public class LecturerStudyPostViewModel : ILecturerStudyPostModel
    {
        [Column(visible: false)]
        public int Id { get; set; }
        [Column(title: "", width: 100)]
        public string StudyPostTitle { get; set; } = string.Empty;
        [Column(title: "", width: 100)]
        public int Hours { get; set; }
    }
}
