// <auto-generated />

using DepartmentDataModels.Enums;
using DepartmentDataModels.Models;
using DepartmentContracts.Attributes;

namespace DepartmentContracts.ViewModels
{
    public class LecturerViewModel : ILecturerModel
    {
        [Column(visible: false)]
        public int Id { get; set; }
        [Column(visible: false)]
        public int? LecturerStudyPostId { get; set; }
        [Column(title: "", width: 100)]
        public string LecturerStudyPost { get; set; } = string.Empty;
        [Column(visible: false)]
        public int LecturerDepartmentPostId { get; set; }
        [Column(title: "", width: 100)]
        public string LecturerDepartmentPost { get; set; } = string.Empty;
        [Column(title: "", width: 100)]
        public string FirstName { get; set; } = string.Empty;
        [Column(title: "", width: 100)]
        public string LastName { get; set; } = string.Empty;
        [Column(title: "", width: 100)]
        public string Patronymic { get; set; } = string.Empty;
        [Column(title: "", width: 100)]
        public string Abbreviation { get; set; } = string.Empty;
        [Column(title: "", width: 100)]
        public DateTime DateBirth { get; set; }
        [Column(title: "", width: 100)]
        public string Address { get; set; } = string.Empty;
        [Column(title: "", width: 100)]
        public string Email { get; set; } = string.Empty;
        [Column(title: "", width: 100)]
        public string MobileNumber { get; set; } = string.Empty;
        [Column(title: "", width: 100)]
        public string HomeNumber { get; set; } = string.Empty;
        [Column(title: "", width: 100)]
        public Rank Rank { get; set; }
        [Column(title: "", width: 100)]
        public Rank2 Rank2 { get; set; }
        [Column(title: "", width: 100)]
        public string Description { get; set; } = string.Empty;
        [Column(visible: false)]
        public byte[] Photo { get; set; }
        [Column(title: "", width: 100)]
        public bool OnlyForPrivate { get; set; }
    }
}
