// <auto-generated />

using DepartmentDataModels.Models;
using DepartmentContracts.Attributes;

namespace DepartmentContracts.ViewModels
{
    public class LecturerDepartmentPostViewModel : ILecturerDepartmentPostModel
    {
        [Column(visible: false)]
        public int Id { get; set; }
        [Column(title: "", width: 100)]
        public string DepartmentPostTitle { get; set; } = string.Empty;
        [Column(title: "", width: 100)]
        public int Order { get; set; }
    }
}
