// <auto-generated />

using DepartmentDataModels.Enums;
using DepartmentDataModels.Models;
using DepartmentContracts.Attributes;

namespace DepartmentContracts.ViewModels
{
    public class StudentViewModel : IStudentModel
    {
        [Column(visible: false)]
        public int Id { get; set; }
        [Column(visible: false)]
        public int? StudentGroupId { get; set; }
        [Column(title: "", width: 100)]
        public string StudentGroup { get; set; } = string.Empty;
        [Column(title: "", width: 100)]
        public string NumberOfBook { get; set; } = string.Empty;
        [Column(title: "", width: 100)]
        public string FirstName { get; set; } = string.Empty;
        [Column(title: "", width: 100)]
        public string LastName { get; set; } = string.Empty;
        [Column(title: "", width: 100)]
        public string Patronymic { get; set; } = string.Empty;
        [Column(title: "", width: 100)]
        public string Email { get; set; } = string.Empty;
        [Column(title: "", width: 100)]
        public StudentState StudentState { get; set; }
        [Column(title: "", width: 100)]
        public string Description { get; set; } = string.Empty;
        [Column(visible: false)]
        public byte[] Photo { get; set; }
        [Column(title: "", width: 100)]
        public bool IsSteward { get; set; }
    }
}
