// <auto-generated />

using DepartmentDataModels.Enums;
using DepartmentDataModels.Models;
using DepartmentContracts.Attributes;

namespace DepartmentContracts.ViewModels
{
    public class StudentGroupViewModel : IStudentGroupModel
    {
        [Column(visible: false)]
        public int Id { get; set; }
        [Column(visible: false)]
        public int EducationDirectionId { get; set; }
        [Column(title: "", width: 100)]
        public string EducationDirection { get; set; } = string.Empty;
        [Column(visible: false)]
        public int? CuratorId { get; set; }
        [Column(title: "", width: 100)]
        public string Curator { get; set; } = string.Empty;
        [Column(title: "", width: 100)]
        public string GroupName { get; set; } = string.Empty;
        [Column(title: "", width: 100)]
        public AcademicCourse Course { get; set; }
    }
}
