// <auto-generated />

using DepartmentDataModels.Models;
using DepartmentContracts.Attributes;

namespace DepartmentContracts.ViewModels
{
    public class StudentOrderBlockStudentViewModel : IStudentOrderBlockStudentModel
    {
        [Column(visible: false)]
        public int Id { get; set; }
        [Column(visible: false)]
        public int StudentOrderBlockId { get; set; }
        [Column(title: "", width: 100)]
        public string StudentOrderBlock { get; set; } = string.Empty;
        [Column(visible: false)]
        public int StudentId { get; set; }
        [Column(title: "", width: 100)]
        public string Student { get; set; } = string.Empty;
        [Column(visible: false)]
        public int? StudentGroupFromId { get; set; }
        [Column(title: "", width: 100)]
        public string? StudentGroupFrom { get; set; } = string.Empty;
        [Column(visible: false)]
        public int? StudentGroupToId { get; set; }
        [Column(title: "", width: 100)]
        public string? StudentGroupTo { get; set; } = string.Empty;
    }
}
