// <auto-generated />

using DepartmentDataModels.Enums;
using DepartmentDataModels.Models;
using DepartmentContracts.Attributes;

namespace DepartmentContracts.ViewModels
{
    public class StudentOrderViewModel : IStudentOrderModel
    {
        [Column(visible: false)]
        public int Id { get; set; }
        [Column(title: "", width: 100)]
        public string OrderNumber { get; set; } = string.Empty;
        [Column(title: "", width: 100)]
        public StudentOrderType StudentOrderType { get; set; }
    }
}
