// <auto-generated />

using DepartmentDataModels.Enums;
using DepartmentDataModels.Models;
using DepartmentContracts.Attributes;

namespace DepartmentContracts.ViewModels
{
    public class StudentOrderBlockViewModel : IStudentOrderBlockModel
    {
        [Column(visible: false)]
        public int Id { get; set; }
        [Column(visible: false)]
        public int StudentOrderId { get; set; }
        [Column(title: "", width: 100)]
        public string StudentOrder { get; set; } = string.Empty;
        [Column(visible: false)]
        public int EducationDirectionId { get; set; }
        [Column(title: "", width: 100)]
        public string EducationDirection { get; set; } = string.Empty;
        [Column(title: "", width: 100)]
        public StudentOrderType StudentOrderType { get; set; }
    }
}
