// <auto-generated />

using DepartmentDataModels.Enums;
using DepartmentDataModels.Models;

namespace DepartmentContracts.BindingModels
{
    public class AcademicPlanRecordBindingModel : IAcademicPlanRecordModel
    {
        public int Id { get; set; }
        public int AcademicPlanId { get; set; }
        public int DisciplineId { get; set; }
        public int? AcademicPlanRecordParentId { get; set; }
        public bool InDepartment { get; set; }
        public Semesters Semester { get; set; }
        public int Zet { get; set; }
        public bool IsParent { get; set; }
        public bool IsChild { get; set; }
        public bool IsFacultative { get; set; }
        public bool IsUseInWorkload { get; set; }
        public bool IsActiveSemester { get; set; }
    }
}
