// <auto-generated />

using DepartmentDataModels.Enums;
using DepartmentDataModels.Models;

namespace DepartmentContracts.BindingModels
{
    public class AcademicPlanBindingModel : IAcademicPlanModel
    {
        public int Id { get; set; }
        public int? EducationDirectionId { get; set; }
        public EducationForm EducationForm { get; set; }
        public AcademicCourse AcademicCourses { get; set; }
        public string Year { get; set; }
    }
}
