// <auto-generated />

using DepartmentDataModels.Enums;
using DepartmentDataModels.Models;

namespace DepartmentContracts.BindingModels
{
    public class ClassroomBindingModel : IClassroomModel
    {
        public int Id { get; set; }
        public string Number { get; set; } = string.Empty;
        public ClassroomTypes Type { get; set; }
        public int Capacity { get; set; }
        public bool NotUseInSchedule { get; set; }
        public bool HasProjector { get; set; }
    }
}
