// <auto-generated />

using DepartmentDataModels.Models;

namespace DepartmentContracts.BindingModels
{
    public class DisciplineBlockBindingModel : IDisciplineBlockModel
    {
        public int Id { get; set; }
        public string Title { get; set; } = string.Empty;
        public string DisciplineBlockBlueAsteriskName { get; set; } = string.Empty;
        public bool DisciplineBlockUseForGrouping { get; set; }
        public int DisciplineBlockOrder { get; set; }
    }
}
