// <auto-generated />

using DepartmentDataModels.Enums;
using DepartmentDataModels.Models;

namespace DepartmentContracts.BindingModels
{
    public class DisciplineStudentRecordBindingModel : IDisciplineStudentRecordModel
    {
        public int Id { get; set; }
        public int DisciplineId { get; set; }
        public int StudentId { get; set; }
        public Semesters Semester { get; set; }
        public string Variant { get; set; } = string.Empty;
        public int SubGroup { get; set; }
        public MarkType MarkType { get; set; }
    }
}
