// <auto-generated />

using DepartmentDataModels.Enums;
using DepartmentDataModels.Models;

namespace DepartmentContracts.BindingModels
{
    public class EducationDirectionBindingModel : IEducationDirectionModel
    {
        public int Id { get; set; }
        public string Cipher { get; set; } = string.Empty;
        public string ShortName { get; set; } = string.Empty;
        public string Title { get; set; } = string.Empty;
        public EducationDirectionQualification Qualification { get; set; }
        public string Profile { get; set; } = string.Empty;
        public string Description { get; set; } = string.Empty;
    }
}
