// <auto-generated />

using DepartmentDataModels.Enums;
using DepartmentDataModels.Models;

namespace DepartmentContracts.BindingModels
{
    public class LecturerBindingModel : ILecturerModel
    {
        public int Id { get; set; }
        public int? LecturerStudyPostId { get; set; }
        public int LecturerDepartmentPostId { get; set; }
        public string FirstName { get; set; } = string.Empty;
        public string LastName { get; set; } = string.Empty;
        public string Patronymic { get; set; } = string.Empty;
        public string Abbreviation { get; set; } = string.Empty;
        public DateTime DateBirth { get; set; }
        public string Address { get; set; } = string.Empty;
        public string Email { get; set; } = string.Empty;
        public string MobileNumber { get; set; } = string.Empty;
        public string HomeNumber { get; set; } = string.Empty;
        public Rank Rank { get; set; }
        public Rank2 Rank2 { get; set; }
        public string Description { get; set; } = string.Empty;
        public byte[] Photo { get; set; }
        public bool OnlyForPrivate { get; set; }
    }
}
