// <auto-generated />

using DepartmentDataModels.Models;

namespace DepartmentContracts.BindingModels
{
    public class LecturerDepartmentPostBindingModel : ILecturerDepartmentPostModel
    {
        public int Id { get; set; }
        public string DepartmentPostTitle { get; set; } = string.Empty;
        public int Order { get; set; }
    }
}
