// <auto-generated />

using DepartmentDataModels.Models;

namespace DepartmentContracts.BindingModels
{
    public class LecturerStudyPostBindingModel : ILecturerStudyPostModel
    {
        public int Id { get; set; }
        public string StudyPostTitle { get; set; } = string.Empty;
        public int Hours { get; set; }
    }
}
