// <auto-generated />

using DepartmentDataModels.Enums;
using DepartmentDataModels.Models;

namespace DepartmentContracts.BindingModels
{
    public class StudentGroupBindingModel : IStudentGroupModel
    {
        public int Id { get; set; }
        public int EducationDirectionId { get; set; }
        public int? CuratorId { get; set; }
        public string GroupName { get; set; } = string.Empty;
        public AcademicCourse Course { get; set; }
    }
}
