// <auto-generated />

using DepartmentDataModels.Enums;
using DepartmentDataModels.Models;

namespace DepartmentContracts.BindingModels
{
    public class StudentOrderBlockBindingModel : IStudentOrderBlockModel
    {
        public int Id { get; set; }
        public int StudentOrderId { get; set; }
        public int EducationDirectionId { get; set; }
        public StudentOrderType StudentOrderType { get; set; }
    }
}
