// <auto-generated />

using DepartmentDataModels.Enums;
using DepartmentDataModels.Models;

namespace DepartmentContracts.BindingModels
{
    public class StudentOrderBindingModel : IStudentOrderModel
    {
        public int Id { get; set; }
        public string OrderNumber { get; set; } = string.Empty;
        public StudentOrderType StudentOrderType { get; set; }
    }
}
