// <auto-generated />
using System.Collections.Generic;
using DepartmentContracts.BindingModels;
using DepartmentContracts.SearchModels;
using DepartmentContracts.ViewModels;

namespace DepartmentContracts.StoragesContracts
{
    public interface IAcademicPlanStorage
    {
        List<AcademicPlanViewModel> GetFullList();
        List<AcademicPlanViewModel> GetFilteredList(AcademicPlanSearchModel model);
        AcademicPlanViewModel? GetElement(AcademicPlanSearchModel model);
        AcademicPlanViewModel? Insert(AcademicPlanBindingModel model);
        AcademicPlanViewModel? Update(AcademicPlanBindingModel model);
        AcademicPlanViewModel? Delete(AcademicPlanBindingModel model);
    }
}
