// <auto-generated />
using System.Collections.Generic;
using DepartmentContracts.BindingModels;
using DepartmentContracts.SearchModels;
using DepartmentContracts.ViewModels;

namespace DepartmentContracts.StoragesContracts
{
    public interface IAcademicPlanRecordStorage
    {
        List<AcademicPlanRecordViewModel> GetFullList();
        List<AcademicPlanRecordViewModel> GetFilteredList(AcademicPlanRecordSearchModel model);
        AcademicPlanRecordViewModel? GetElement(AcademicPlanRecordSearchModel model);
        AcademicPlanRecordViewModel? Insert(AcademicPlanRecordBindingModel model);
        AcademicPlanRecordViewModel? Update(AcademicPlanRecordBindingModel model);
        AcademicPlanRecordViewModel? Delete(AcademicPlanRecordBindingModel model);
    }
}
