// <auto-generated />
using System.Collections.Generic;
using DepartmentContracts.BindingModels;
using DepartmentContracts.SearchModels;
using DepartmentContracts.ViewModels;

namespace DepartmentContracts.StoragesContracts
{
    public interface IClassroomStorage
    {
        List<ClassroomViewModel> GetFullList();
        List<ClassroomViewModel> GetFilteredList(ClassroomSearchModel model);
        ClassroomViewModel? GetElement(ClassroomSearchModel model);
        ClassroomViewModel? Insert(ClassroomBindingModel model);
        ClassroomViewModel? Update(ClassroomBindingModel model);
        ClassroomViewModel? Delete(ClassroomBindingModel model);
    }
}
