// <auto-generated />
using System.Collections.Generic;
using DepartmentContracts.BindingModels;
using DepartmentContracts.SearchModels;
using DepartmentContracts.ViewModels;

namespace DepartmentContracts.StoragesContracts
{
    public interface IDisciplineStorage
    {
        List<DisciplineViewModel> GetFullList();
        List<DisciplineViewModel> GetFilteredList(DisciplineSearchModel model);
        DisciplineViewModel? GetElement(DisciplineSearchModel model);
        DisciplineViewModel? Insert(DisciplineBindingModel model);
        DisciplineViewModel? Update(DisciplineBindingModel model);
        DisciplineViewModel? Delete(DisciplineBindingModel model);
    }
}
