// <auto-generated />
using System.Collections.Generic;
using DepartmentContracts.BindingModels;
using DepartmentContracts.SearchModels;
using DepartmentContracts.ViewModels;

namespace DepartmentContracts.StoragesContracts
{
    public interface IDisciplineBlockStorage
    {
        List<DisciplineBlockViewModel> GetFullList();
        List<DisciplineBlockViewModel> GetFilteredList(DisciplineBlockSearchModel model);
        DisciplineBlockViewModel? GetElement(DisciplineBlockSearchModel model);
        DisciplineBlockViewModel? Insert(DisciplineBlockBindingModel model);
        DisciplineBlockViewModel? Update(DisciplineBlockBindingModel model);
        DisciplineBlockViewModel? Delete(DisciplineBlockBindingModel model);
    }
}
