// <auto-generated />
using System.Collections.Generic;
using DepartmentContracts.BindingModels;
using DepartmentContracts.SearchModels;
using DepartmentContracts.ViewModels;

namespace DepartmentContracts.StoragesContracts
{
    public interface IDisciplineStudentRecordStorage
    {
        List<DisciplineStudentRecordViewModel> GetFullList();
        List<DisciplineStudentRecordViewModel> GetFilteredList(DisciplineStudentRecordSearchModel model);
        DisciplineStudentRecordViewModel? GetElement(DisciplineStudentRecordSearchModel model);
        DisciplineStudentRecordViewModel? Insert(DisciplineStudentRecordBindingModel model);
        DisciplineStudentRecordViewModel? Update(DisciplineStudentRecordBindingModel model);
        DisciplineStudentRecordViewModel? Delete(DisciplineStudentRecordBindingModel model);
    }
}
