// <auto-generated />
using System.Collections.Generic;
using DepartmentContracts.BindingModels;
using DepartmentContracts.SearchModels;
using DepartmentContracts.ViewModels;

namespace DepartmentContracts.StoragesContracts
{
    public interface IEducationDirectionStorage
    {
        List<EducationDirectionViewModel> GetFullList();
        List<EducationDirectionViewModel> GetFilteredList(EducationDirectionSearchModel model);
        EducationDirectionViewModel? GetElement(EducationDirectionSearchModel model);
        EducationDirectionViewModel? Insert(EducationDirectionBindingModel model);
        EducationDirectionViewModel? Update(EducationDirectionBindingModel model);
        EducationDirectionViewModel? Delete(EducationDirectionBindingModel model);
    }
}
