// <auto-generated />
using System.Collections.Generic;
using DepartmentContracts.BindingModels;
using DepartmentContracts.SearchModels;
using DepartmentContracts.ViewModels;

namespace DepartmentContracts.StoragesContracts
{
    public interface ILecturerStudyPostStorage
    {
        List<LecturerStudyPostViewModel> GetFullList();
        List<LecturerStudyPostViewModel> GetFilteredList(LecturerStudyPostSearchModel model);
        LecturerStudyPostViewModel? GetElement(LecturerStudyPostSearchModel model);
        LecturerStudyPostViewModel? Insert(LecturerStudyPostBindingModel model);
        LecturerStudyPostViewModel? Update(LecturerStudyPostBindingModel model);
        LecturerStudyPostViewModel? Delete(LecturerStudyPostBindingModel model);
    }
}
