// <auto-generated />
using System.Collections.Generic;
using DepartmentContracts.BindingModels;
using DepartmentContracts.SearchModels;
using DepartmentContracts.ViewModels;

namespace DepartmentContracts.StoragesContracts
{
    public interface ILecturerStorage
    {
        List<LecturerViewModel> GetFullList();
        List<LecturerViewModel> GetFilteredList(LecturerSearchModel model);
        LecturerViewModel? GetElement(LecturerSearchModel model);
        LecturerViewModel? Insert(LecturerBindingModel model);
        LecturerViewModel? Update(LecturerBindingModel model);
        LecturerViewModel? Delete(LecturerBindingModel model);
    }
}
