// <auto-generated />
using System.Collections.Generic;
using DepartmentContracts.BindingModels;
using DepartmentContracts.SearchModels;
using DepartmentContracts.ViewModels;

namespace DepartmentContracts.StoragesContracts
{
    public interface ILecturerDepartmentPostStorage
    {
        List<LecturerDepartmentPostViewModel> GetFullList();
        List<LecturerDepartmentPostViewModel> GetFilteredList(LecturerDepartmentPostSearchModel model);
        LecturerDepartmentPostViewModel? GetElement(LecturerDepartmentPostSearchModel model);
        LecturerDepartmentPostViewModel? Insert(LecturerDepartmentPostBindingModel model);
        LecturerDepartmentPostViewModel? Update(LecturerDepartmentPostBindingModel model);
        LecturerDepartmentPostViewModel? Delete(LecturerDepartmentPostBindingModel model);
    }
}
