// <auto-generated />
using System.Collections.Generic;
using DepartmentContracts.BindingModels;
using DepartmentContracts.SearchModels;
using DepartmentContracts.ViewModels;

namespace DepartmentContracts.StoragesContracts
{
    public interface IStudentOrderStorage
    {
        List<StudentOrderViewModel> GetFullList();
        List<StudentOrderViewModel> GetFilteredList(StudentOrderSearchModel model);
        StudentOrderViewModel? GetElement(StudentOrderSearchModel model);
        StudentOrderViewModel? Insert(StudentOrderBindingModel model);
        StudentOrderViewModel? Update(StudentOrderBindingModel model);
        StudentOrderViewModel? Delete(StudentOrderBindingModel model);
    }
}
