// <auto-generated />
using System.Collections.Generic;
using DepartmentContracts.BindingModels;
using DepartmentContracts.SearchModels;
using DepartmentContracts.ViewModels;

namespace DepartmentContracts.StoragesContracts
{
    public interface IStudentOrderBlockStorage
    {
        List<StudentOrderBlockViewModel> GetFullList();
        List<StudentOrderBlockViewModel> GetFilteredList(StudentOrderBlockSearchModel model);
        StudentOrderBlockViewModel? GetElement(StudentOrderBlockSearchModel model);
        StudentOrderBlockViewModel? Insert(StudentOrderBlockBindingModel model);
        StudentOrderBlockViewModel? Update(StudentOrderBlockBindingModel model);
        StudentOrderBlockViewModel? Delete(StudentOrderBlockBindingModel model);
    }
}
