// <auto-generated />
using System.Collections.Generic;
using DepartmentContracts.BindingModels;
using DepartmentContracts.SearchModels;
using DepartmentContracts.ViewModels;

namespace DepartmentContracts.StoragesContracts
{
    public interface IStudentGroupStorage
    {
        List<StudentGroupViewModel> GetFullList();
        List<StudentGroupViewModel> GetFilteredList(StudentGroupSearchModel model);
        StudentGroupViewModel? GetElement(StudentGroupSearchModel model);
        StudentGroupViewModel? Insert(StudentGroupBindingModel model);
        StudentGroupViewModel? Update(StudentGroupBindingModel model);
        StudentGroupViewModel? Delete(StudentGroupBindingModel model);
    }
}
