// <auto-generated />
using System.Collections.Generic;
using DepartmentContracts.BindingModels;
using DepartmentContracts.SearchModels;
using DepartmentContracts.ViewModels;

namespace DepartmentContracts.StoragesContracts
{
    public interface IStudentOrderBlockStudentStorage
    {
        List<StudentOrderBlockStudentViewModel> GetFullList();
        List<StudentOrderBlockStudentViewModel> GetFilteredList(StudentOrderBlockStudentSearchModel model);
        StudentOrderBlockStudentViewModel? GetElement(StudentOrderBlockStudentSearchModel model);
        StudentOrderBlockStudentViewModel? Insert(StudentOrderBlockStudentBindingModel model);
        StudentOrderBlockStudentViewModel? Update(StudentOrderBlockStudentBindingModel model);
        StudentOrderBlockStudentViewModel? Delete(StudentOrderBlockStudentBindingModel model);
    }
}
